### ISSUE TITLE
安装elasticsearch-sql 后 启动 elasticsearch报错

### ISSUE THREAD

**Issue by junbao520** [NLPchina/elasticsearch-sql#1017]
java.lang.IllegalArgumentException: Cannot replace existing handler for [/_sql] for method: POST
	at org.elasticsearch.rest.MethodHandlers.addMethods(MethodHandlers.java:52) ~[elasticsearch-7.4.2.jar:7.4.2]
	at org.elasticsearch.rest.RestController.lambda$registerHandler$1(RestController.java:156) ~[elasticsearch-7.4.2.jar:7.4.2]
	at org.elasticsearch.common.path.PathTrie$TrieNode.insertOrUpdate(PathTrie.java:167) ~[elasticsearch-7.4.2.jar:7.4.2]
	at org.elasticsearch.common.path.PathTrie$TrieNode.access$400(PathTrie.java:76) ~[elasticsearch-7.4.2.jar:7.4.2]
	at org.elasticsearch.common.path.PathTrie.insertOrUpdate(PathTrie.java:316) ~[elasticsearch-7.4.2.jar:7.4.2]
	at org.elasticsearch.rest.RestController.registerHandler(RestController.java:155) ~[elasticsearch-7.4.2.jar:7.4.2]
	at org.elasticsearch.plugin.nlpcn.RestSqlAction.<init>(RestSqlAction.java:35) ~[?:?]
	at org.elasticsearch.plugin.nlpcn.SqlPlug.getRestHandlers(SqlPlug.java:35) ~[?:?]
	at org.elasticsearch.action.ActionModule.initRestHandlers(ActionModule.java:692) ~[elasticsearch-7.4.2.jar:7.4.2]
	at org.elasticsearch.node.Node.<init>(Node.java:609) ~[elasticsearch-7.4.2.jar:7.4.2]
	at org.elasticsearch.node.Node.<init>(Node.java:255) ~[elasticsearch-7.4.2.jar:7.4.2]
	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:221) ~[elasticsearch-7.4.2.jar:7.4.2]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:221) ~[elasticsearch-7.4.2.jar:7.4.2]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:349) [elasticsearch-7.4.2.jar:7.4.2]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159) [elasticsearch-7.4.2.jar:7.4.2]
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:150) [elasticsearch-7.4.2.jar:7.4.2]
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) [elasticsearch-7.4.2.jar:7.4.2]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:125) [elasticsearch-cli-7.4.2.jar:7.4.2]
	at org.elasticsearch.cli.Command.main(Command.java:90) [elasticsearch-cli-7.4.2.jar:7.4.2]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:115) [elasticsearch-7.4.2.jar:7.4.2]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92) [elasticsearch-7.4.2.jar:7.4.2]

**Comment by dai-chen** [comment]
@junbao520 https://github.com/NLPchina/elasticsearch-sql/issues/1006#issuecomment-554754589

**Comment by junbao520** [comment]
> @junbao520 [#1006 (comment)](https://github.com/NLPchina/elasticsearch-sql/issues/1006#issuecomment-554754589)
谢谢，有详细的安装配置文档么？

**Comment by dai-chen** [comment]
> > @junbao520 [#1006 (comment)](https://github.com/NLPchina/elasticsearch-sql/issues/1006#issuecomment-554754589)
> > 谢谢，有详细的安装配置文档么？

因为NLPchina不再维护了，所以这个路径冲突应该不会解决了。你可以试一下我正在做的https://github.com/opendistro-for-elasticsearch/sql

这是我之前发的声明：https://github.com/NLPchina/elasticsearch-sql/issues/1006#issuecomment-558347934

**Comment by junbao520** [comment]
好的！ 我试试 您这个项目！ 有不明白的在请教您！&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Chen Dai"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月5日(星期四) 下午2:48
收件人:&nbsp;"NLPchina/elasticsearch-sql"<elasticsearch-sql@noreply.github.com&gt;;
抄送:&nbsp;"等待。情缘"<757114760@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [NLPchina/elasticsearch-sql] 安装elasticsearch-sql 后 启动 elasticsearch报错 (#1017)



  
@junbao520 #1006 (comment)
 谢谢，有详细的安装配置文档么？
   
因为NLPchina不再维护了，所以这个路径冲突应该不会解决了。你可以试一下我正在做的https://github.com/opendistro-for-elasticsearch/sql
 
这是我之前发的声明：#1006 (comment)

**Comment by dai-chen** [comment]
> 好的！ 我试试 您这个项目！ 有不明白的在请教您！&nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"Chen Dai"<notifications@github.com&gt;; 发送时间:&nbsp;2019年12月5日(星期四) 下午2:48 收件人:&nbsp;"NLPchina/elasticsearch-sql"<elasticsearch-sql@noreply.github.com&gt;; 抄送:&nbsp;"等待。情缘"<757114760@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;; 主题:&nbsp;Re: [NLPchina/elasticsearch-sql] 安装elasticsearch-sql 后 启动 elasticsearch报错 (#1017) @junbao520 #1006 (comment) 谢谢，有详细的安装配置文档么？ 因为NLPchina不再维护了，所以这个路径冲突应该不会解决了。你可以试一下我正在做的https://github.com/opendistro-for-elasticsearch/sql 这是我之前发的声明：#1006 (comment) — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

没问题！:)

**Comment by junbao520** [comment]
icrosoft Windows [版本 10.0.18362.30]
(c) 2019 Microsoft Corporation。保留所有权利。


C:\Users\Administrator&gt;e:


E:\&gt;cd E:\sql-master


E:\sql-master&gt;gradlew build
Downloading https://services.gradle.org/distributions/gradle-5.5.1-bin.zip


Exception in thread "main" javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake
&nbsp; &nbsp; &nbsp; &nbsp; at java.base/sun.security.ssl.SSLSocketImpl.handleEOF(SSLSocketImpl.java:1659)
&nbsp; &nbsp; &nbsp; &nbsp; at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1468)
&nbsp; &nbsp; &nbsp; &nbsp; at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1368)
&nbsp; &nbsp; &nbsp; &nbsp; at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:437)
&nbsp; &nbsp; &nbsp; &nbsp; at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:567)
&nbsp; &nbsp; &nbsp; &nbsp; at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:171)
&nbsp; &nbsp; &nbsp; &nbsp; at java.base/sun.net.www.protocol.http.HttpURLConnection.followRedirect0(HttpURLConnection.java:2778)
&nbsp; &nbsp; &nbsp; &nbsp; at java.base/sun.net.www.protocol.http.HttpURLConnection.followRedirect(HttpURLConnection.java:2690)
&nbsp; &nbsp; &nbsp; &nbsp; at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1849)
&nbsp; &nbsp; &nbsp; &nbsp; at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1515)
&nbsp; &nbsp; &nbsp; &nbsp; at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
&nbsp; &nbsp; &nbsp; &nbsp; at org.gradle.wrapper.Download.downloadInternal(Download.java:67)
&nbsp; &nbsp; &nbsp; &nbsp; at org.gradle.wrapper.Download.download(Download.java:52)
&nbsp; &nbsp; &nbsp; &nbsp; at org.gradle.wrapper.Install$1.call(Install.java:62)
&nbsp; &nbsp; &nbsp; &nbsp; at org.gradle.wrapper.Install$1.call(Install.java:48)
&nbsp; &nbsp; &nbsp; &nbsp; at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:69)
&nbsp; &nbsp; &nbsp; &nbsp; at org.gradle.wrapper.Install.createDist(Install.java:48)
&nbsp; &nbsp; &nbsp; &nbsp; at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)
&nbsp; &nbsp; &nbsp; &nbsp; at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:63)
Caused by: java.io.EOFException: SSL peer shut down incorrectly
&nbsp; &nbsp; &nbsp; &nbsp; at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:167)
&nbsp; &nbsp; &nbsp; &nbsp; at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:108)
&nbsp; &nbsp; &nbsp; &nbsp; at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1460)
&nbsp; &nbsp; &nbsp; &nbsp; ... 17 more


E:\sql-master&gt;





报错了！ 我不知道是不是这样构建的。因为我不是java开发人员，所以我没办法使用编译器打开您的项目进行编译！&nbsp;
您是否有提供已经编译好的版本！ 可以直接供其他开发人员或者维护人员直接安装的了？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Chen Dai"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月5日(星期四) 下午2:54
收件人:&nbsp;"NLPchina/elasticsearch-sql"<elasticsearch-sql@noreply.github.com&gt;;
抄送:&nbsp;"等待。情缘"<757114760@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [NLPchina/elasticsearch-sql] 安装elasticsearch-sql 后 启动 elasticsearch报错 (#1017)



 
好的！ 我试试 您这个项目！ 有不明白的在请教您！&nbsp;
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"Chen Dai"<notifications@github.com&gt;; 发送时间:&nbsp;2019年12月5日(星期四) 下午2:48 收件人:&nbsp;"NLPchina/elasticsearch-sql"<elasticsearch-sql@noreply.github.com&gt;; 抄送:&nbsp;"等待。情缘"<757114760@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;; 主题:&nbsp;Re: [NLPchina/elasticsearch-sql] 安装elasticsearch-sql 后 启动 elasticsearch报错 (#1017) @junbao520 #1006 (comment) 谢谢，有详细的安装配置文档么？ 因为NLPchina不再维护了，所以这个路径冲突应该不会解决了。你可以试一下我正在做的https://github.com/opendistro-for-elasticsearch/sql 这是我之前发的声明：#1006 (comment) — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.
  
没问题！:)

**Comment by dai-chen** [comment]
有的，我们提供了不同的分发包，你可以直接下载：https://opendistro.github.io/for-elasticsearch/downloads.html。再有问题欢迎给我们开Issue。
