### ISSUE TITLE
7.3.0启动报错

### ISSUE THREAD

**Issue by fuhongyuan** [NLPchina/elasticsearch-sql#1052]
报错信息如下：
``
uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: java.lang.IllegalArgumentException: Cannot replace existing handler for [/_sql] for method: POST
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:163) ~[elasticsearch-7.3.0.jar:7.3.0]
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:150) ~[elasticsearch-7.3.0.jar:7.3.0]
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) ~[elasticsearch-7.3.0.jar:7.3.0]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) ~[elasticsearch-cli-7.3.0.jar:7.3.0]
	at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-cli-7.3.0.jar:7.3.0]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:115) ~[elasticsearch-7.3.0.jar:7.3.0]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92) ~[elasticsearch-7.3.0.jar:7.3.0]
Caused by: java.lang.IllegalArgumentException: Cannot replace existing handler for [/_sql] for method: POST
	at org.elasticsearch.rest.MethodHandlers.addMethod(MethodHandlers.java:50) ~[elasticsearch-7.3.0.jar:7.3.0]
	at org.elasticsearch.rest.MethodHandlers.addMethods(MethodHandlers.java:61) ~[elasticsearch-7.3.0.jar:7.3.0]
	at org.elasticsearch.rest.RestController.lambda$registerHandler$1(RestController.java:156) ~[elasticsearch-7.3.0.jar:7.3.0]
	at org.elasticsearch.common.path.PathTrie$TrieNode.insertOrUpdate(PathTrie.java:172) ~[elasticsearch-7.3.0.jar:7.3.0]
	at org.elasticsearch.common.path.PathTrie.insertOrUpdate(PathTrie.java:321) ~[elasticsearch-7.3.0.jar:7.3.0]
	at org.elasticsearch.rest.RestController.registerHandler(RestController.java:155) ~[elasticsearch-7.3.0.jar:7.3.0]
	at org.elasticsearch.plugin.nlpcn.RestSqlAction.<init>(RestSqlAction.java:29) ~[?:?]
	at org.elasticsearch.plugin.nlpcn.SqlPlug.getRestHandlers(SqlPlug.java:35) ~[?:?]
	at org.elasticsearch.action.ActionModule.initRestHandlers(ActionModule.java:686) ~[elasticsearch-7.3.0.jar:7.3.0]
	at org.elasticsearch.node.Node.<init>(Node.java:612) ~[elasticsearch-7.3.0.jar:7.3.0]
	at org.elasticsearch.node.Node.<init>(Node.java:258) ~[elasticsearch-7.3.0.jar:7.3.0]
	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:221) ~[elasticsearch-7.3.0.jar:7.3.0]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:221) ~[elasticsearch-7.3.0.jar:7.3.0]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:349) ~[elasticsearch-7.3.0.jar:7.3.0]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159) ~[elasticsearch-7.3.0.jar:7.3.0]
	... 6 more
``

**Comment by shi-yuan** [comment]
_sql这个path已被官方占用了，新版本已更换path

https://github.com/NLPchina/elasticsearch-sql#important

**Comment by fuhongyuan** [comment]
好的谢谢
