### ISSUE TITLE
user、

### ISSUE THREAD

**Issue by pengfeng1** [NLPchina/elasticsearch-sql#1096]
17:20:35,673 ERROR com.alibaba.druid.pool.DruidDataSource                        - create connection error
java.lang.InstantiationError: org.elasticsearch.common.transport.TransportAddress
	at com.alibaba.druid.pool.ElasticSearchConnection.<init>(ElasticSearchConnection.java:40)
	at com.alibaba.druid.pool.ElasticSearchDruidDataSource.createPhysicalConnection(ElasticSearchDruidDataSource.java:658)
	at com.alibaba.druid.pool.ElasticSearchDruidDataSource.createPhysicalConnection(ElasticSearchDruidDataSource.java:623)
	at com.alibaba.druid.pool.ElasticSearchDruidDataSource$CreateConnectionThread.run(ElasticSearchDruidDataSource.java:1802)

**Comment by pengfeng1** [comment]
<dependencies>
        
        <dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
            <version>5.1.49</version>
        </dependency>

        <dependency>
            <groupId>org.elasticsearch.client</groupId>
            <artifactId>x-pack-transport</artifactId>
            <version>5.6.1</version>
        </dependency>


        <dependency>
            <groupId>org.nlpcn</groupId>
            <artifactId>elasticsearch-sql</artifactId>
            <version>6.2.2.0</version>
        </dependency>

**Comment by shi-yuan** [comment]
`java.lang.InstantiationError: org.elasticsearch.common.transport.TransportAddress`？？？
