### ISSUE TITLE
7.0.1版本安装对应版本的插件，启动es报错

### ISSUE THREAD

**Issue by xingdong123** [NLPchina/elasticsearch-sql#1107]
7.0.1版本安装插件后启动报错，错误如下
`[2020-10-27T15:54:59,227][INFO ][o.e.d.DiscoveryModule    ] [172.16.10.231] using discovery type [zen] and seed hosts providers [settings]
[2020-10-27T15:55:00,050][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [172.16.10.231] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: java.lang.IllegalArgumentException: Cannot replace existing handler for [/_sql] for method: POST
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:163) ~[elasticsearch-7.0.1.jar:7.0.1]
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:150) ~[elasticsearch-7.0.1.jar:7.0.1]
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) ~[elasticsearch-7.0.1.jar:7.0.1]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) ~[elasticsearch-cli-7.0.1.jar:7.0.1]
	at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-cli-7.0.1.jar:7.0.1]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:115) ~[elasticsearch-7.0.1.jar:7.0.1]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92) ~[elasticsearch-7.0.1.jar:7.0.1]
Caused by: java.lang.IllegalArgumentException: Cannot replace existing handler for [/_sql] for method: POST
	at org.elasticsearch.rest.MethodHandlers.addMethod(MethodHandlers.java:50) ~[elasticsearch-7.0.1.jar:7.0.1]
	at org.elasticsearch.rest.MethodHandlers.addMethods(MethodHandlers.java:61) ~[elasticsearch-7.0.1.jar:7.0.1]
	at org.elasticsearch.rest.RestController.lambda$registerHandler$1(RestController.java:156) ~[elasticsearch-7.0.1.jar:7.0.1]
	at org.elasticsearch.common.path.PathTrie$TrieNode.insertOrUpdate(PathTrie.java:172) ~[elasticsearch-7.0.1.jar:7.0.1]
	at org.elasticsearch.common.path.PathTrie.insertOrUpdate(PathTrie.java:321) ~[elasticsearch-7.0.1.jar:7.0.1]
	at org.elasticsearch.rest.RestController.registerHandler(RestController.java:155) ~[elasticsearch-7.0.1.jar:7.0.1]
	at org.elasticsearch.plugin.nlpcn.RestSqlAction.<init>(RestSqlAction.java:29) ~[?:?]
	at org.elasticsearch.plugin.nlpcn.SqlPlug.getRestHandlers(SqlPlug.java:35) ~[?:?]
	at org.elasticsearch.action.ActionModule.initRestHandlers(ActionModule.java:680) ~[elasticsearch-7.0.1.jar:7.0.1]
	at org.elasticsearch.node.Node.<init>(Node.java:575) ~[elasticsearch-7.0.1.jar:7.0.1]
	at org.elasticsearch.node.Node.<init>(Node.java:251) ~[elasticsearch-7.0.1.jar:7.0.1]
	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:211) ~[elasticsearch-7.0.1.jar:7.0.1]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:211) ~[elasticsearch-7.0.1.jar:7.0.1]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:325) ~[elasticsearch-7.0.1.jar:7.0.1]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159) ~[elasticsearch-7.0.1.jar:7.0.1]
	... 6 more
`

**Comment by shi-yuan** [comment]
7.5.0以前，path都是以/_sql打头的，以后由于和官方冲突了改成了/_nlpcn打头了
