### ISSUE TITLE
在项目中集成 elasticsearch-sql.jar （7.5.1.3） 报错

### ISSUE THREAD

**Issue by kk-fan** [NLPchina/elasticsearch-sql#1113]
想在项目中集成 elasticsearch-sql 报错 ：
ava.lang.ClassCastException: com.alibaba.druid.sql.ast.statement.SQLSelectQueryBlock cannot be cast to com.alibaba.druid.sql.dialect.mysql.ast.statement.MySqlSelectQueryBlock
	at org.nlpcn.es4sql.parse.SqlParser.parseSelect(SqlParser.java:61) ~[elasticsearch-sql-7.5.1.3.jar:na]
	at org.nlpcn.es4sql.query.ESActionFactory.create(ESActionFactory.java:65) ~[classes/:na]
	at org.nlpcn.es4sql.SearchDao.explain(SearchDao.java:46) ~[elasticsearch-sql-7.5.1.3.jar:na]
	at com.zfsoft.es.service.aop.MyEnabledToEsServerAspect.doAround(MyEnabledToEsServerAspect.java:102) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_172]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_172]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_172]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_172]
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:644) [spring-aop-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:633) [spring-aop-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70) [spring-aop-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175) [spring-aop-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:95) [spring-aop-5.2.8.RELEASE.jar:5.2.8.RELEASE]

这应该是druid版本 的问题  https://github.com/alibaba/druid/issues/2313
请问有解决方案吗？

**Comment by ansjsun** [comment]
吧你的durid 版本换成1.1.16试试

**Comment by kk-fan** [comment]
> 吧你的durid版本换成1.1.16试试

更换后应该是可以的  但我要做个组件给其它系统作为依赖  如果给druid更换版本估计不行

**Comment by kk-fan** [comment]
> 吧你的durid版本换成1.1.16试试

大佬请教下  MySqlSelectQueryBlock 是  SQLSelectQueryBlock 的子类 为什么会出现 SQLSelectQueryBlock  强制转换为 MySqlSelectQueryBlock 的情况？

**Comment by shi-yuan** [comment]
> > 吧你的durid版本换成1.1.16试试
> 
> 大佬请教下 MySqlSelectQueryBlock 是 SQLSelectQueryBlock 的子类 为什么会出现 SQLSelectQueryBlock 强制转换为 MySqlSelectQueryBlock 的情况？

是的，可以考虑换成，父类SQLSelectQueryBlock
