### ISSUE TITLE
3次select及以上的Union操作报错

### ISSUE THREAD

**Issue by fruitSandwich** [NLPchina/elasticsearch-sql#1143]
SELECT * FROM test union SELECT * FROM test
正常转换为
INFO org.elasticsearch.plugin.nlpcn.QueryActionElasticExecutor - Multi Query Explain:
performing UNION on :
 left query:
{
  "from" : 0,
  "size" : 2
}
 right query:
{
  "from" : 0,
  "size" : 2
}

三个select union
SELECT * FROM test union SELECT * FROM test union SELECT * FROM test

报异常:
Caused by: java.lang.ClassCastException: class com.alibaba.druid.sql.dialect.mysql.ast.statement.MySqlUnionQuery cannot be cast to class com.alibaba.druid.sql.dialect.mysql.ast.statement.MySqlSelectQueryBlock (com.alibaba.druid.sql.dialect.mysql.ast.statement.MySqlUnionQuery and com.alibaba.druid.sql.dialect.mysql.ast.statement.MySqlSelectQueryBlock are in unnamed module of loader 'app')
        at org.nlpcn.es4sql.parse.SqlParser.parseMultiSelect(SqlParser.java:77)
        at org.nlpcn.es4sql.query.ESActionFactory.create(ESActionFactory.java:49)
        at org.nlpcn.es4sql.SearchDao.explain(SearchDao.java:46)
        at com.alibaba.druid.pool.ElasticSearchDruidPooledPreparedStatement.getObjectResult(ElasticSearchDruidPooledPreparedStatement.java:68)
        at com.alibaba.druid.pool.ElasticSearchDruidPooledPreparedStatement.executeQuery(ElasticSearchDruidPooledPreparedStatement.java:45)
        ... 9 more

**Comment by shi-yuan** [comment]
目前不支持3个及以上的
