### ISSUE TITLE
elasticsearch-7.9.2 是集群并带有密码 使用 elasticsearch-sql-7.9.2.0.jar 连接时有问题- org.elasticsearch.index.mapper.MappedFieldType: method <init>()V not found

### ISSUE THREAD

**Issue by suixindong** [NLPchina/elasticsearch-sql#1152]
elasticsearch-7.9.2 是集群并带有密码 使用 elasticsearch-sql-7.9.2.0.jar 连接时有问题
es是集群，并带有密码
elasticsearch.yml中
xpack.security.enabled: true
xpack.security.transport.ssl.enabled: true
xpack.security.transport.ssl.verification_mode: certificate
xpack.security.transport.ssl.keystore.path: certs/elastic-certificates.p12
xpack.security.transport.ssl.truststore.path: certs/elastic-certificates.p12

elasticsearch版本为7.9.2
elasticsearch-sql插件版本为 elasticsearch-sql-7.9.2.0.jar
使用依赖：
        <dependency>
            <groupId>org.elasticsearch.client</groupId>
            <artifactId>x-pack-transport</artifactId>
            <version>7.9.2</version>
        </dependency>

参照jdbc方式写的创建链接
Properties properties = new Properties();
        properties.put(PROP_URL, "jdbc:elasticsearch://192.168.182.229:9350,192.168.182.230:9350,192.168.182.231:9350/alarm-20211117");
        properties.put(PROP_CONNECTIONPROPERTIES, "client.transport.ignore_cluster_name=true");
        properties.put("username", "elastic");
        properties.put("password", "zhjk,123");
DruidDataSource	dds = (DruidDataSource) ElasticSearchDruidDataSourceFactory.createDataSource(properties);
报错如下：
15:54:31.215 [Druid-ConnectionPool-Create-1050349584] ERROR com.alibaba.druid.pool.ElasticSearchDruidDataSource - create connection Error
java.lang.NoSuchMethodError: org.elasticsearch.index.mapper.MappedFieldType: method <init>()V not found
	at org.elasticsearch.percolator.PercolatorFieldMapper$FieldType.<init>(PercolatorFieldMapper.java:207)
	at org.elasticsearch.percolator.PercolatorFieldMapper.<clinit>(PercolatorFieldMapper.java:102)
	at org.elasticsearch.percolator.PercolatorPlugin.getSettings(PercolatorPlugin.java:52)
	at org.elasticsearch.plugins.PluginsService.lambda$getPluginSettings$0(PluginsService.java:91)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:267)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)

**Comment by shi-yuan** [comment]
配置用户名和密码，可以参考：#703

**Comment by shi-yuan** [comment]
配置用户名和密码，可以参考：#703
