### ISSUE TITLE
elasticsearch-7.10.2集群配置x-pack认证后无法执行es-sql查询

### ISSUE THREAD

**Issue by levisLi** [NLPchina/elasticsearch-sql#1181]
Properties properties = new Properties();
        properties.put("url", "jdbc:elasticsearch://cqprod03:9300");
        properties.put(PROP_CONNECTIONPROPERTIES, "client.transport.ignore_cluster_name=true;xpack.security.user=elastic:admin@123");
        DruidDataSource dds = (DruidDataSource) ElasticSearchDruidDataSourceFactory.createDataSource(properties);
        Connection connection = dds.getConnection();
        PreparedStatement ps = connection.prepareStatement("SELECT  * from  test");
        ResultSet resultSet = ps.executeQuery();

报如下错误：
Caused by: NoNodeAvailableException[None of the configured nodes are available: [{#transport#-1}{hIlRGQNbSdaTh9IedRffzw}{cqprod03}{10.128.20.251:9300}]]
	at org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:352)
	at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:248)
	at org.elasticsearch.client.transport.TransportProxyClient.execute(TransportProxyClient.java:57)
	at org.elasticsearch.client.transport.TransportClient.doExecute(TransportClient.java:391)
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:412)
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:401)
	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:45)
	at org.elasticsearch.action.ActionRequestBuilder.get(ActionRequestBuilder.java:52)
	at org.nlpcn.es4sql.query.SqlElasticSearchRequestBuilder.get(SqlElasticSearchRequestBuilder.java:29)
	at org.elasticsearch.plugin.nlpcn.QueryActionElasticExecutor.executeSearchAction(QueryActionElasticExecutor.java:34)
	at org.elasticsearch.plugin.nlpcn.QueryActionElasticExecutor.executeAnyAction(QueryActionElasticExecutor.java:84)
	at com.alibaba.druid.pool.ElasticSearchDruidPooledPreparedStatement.getObjectResult(ElasticSearchDruidPooledPreparedStatement.java:92)
	at com.alibaba.druid.pool.ElasticSearchDruidPooledPreparedStatement.executeQuery(ElasticSearchDruidPooledPreparedStatement.java:40)
	... 26 more

**Comment by shi-yuan** [comment]
直接用transportclient，并，设置用户名和密码，可否访问？

**Comment by leviYX** [comment]
有官方样例代码吗，我这么做仍然报错

**Comment by shi-yuan** [comment]
https://github.com/NLPchina/elasticsearch-sql/issues/703

**Comment by dianbaiyizhong** [comment]
我也遇到了类似问题。。。。后来发现跟es的配置network.host有关（elasticsearch.yml）。。例如可以修改为0.0.0.0
