### ISSUE TITLE
无法支持常量参数，能看看怎么回事么？

### ISSUE THREAD

**Issue by AqooDer** [NLPchina/elasticsearch-sql#1229]
比如：select count(*) as totle,'全系统' as all_sys,1 as state from user where state in(1,8) .
报错如下：Caused by: org.nlpcn.es4sql.exception.SqlParseException: unknown field name : 1
	at org.nlpcn.es4sql.parse.FieldMaker.makeField(FieldMaker.java:97)
	at org.nlpcn.es4sql.parse.SqlParser.findSelect(SqlParser.java:140)
	at org.nlpcn.es4sql.parse.SqlParser.parseSelect(SqlParser.java:88)
	at org.nlpcn.es4sql.parse.SqlParser.parseSelect(SqlParser.java:64)
	at org.nlpcn.es4sql.query.ESActionFactory.create(ESActionFactory.java:65)
	at org.nlpcn.es4sql.SearchDao.explain(SearchDao.java:46)

**Comment by shi-yuan** [comment]
```sql
select count(*) as totle,script("all_sys","'全系统'"),script("state","1") as  from user where state in(1,8) 
```

**Comment by AqooDer** [comment]
感谢
