### ISSUE TITLE
union 两个count查询时报错

### ISSUE THREAD

**Issue by AqooDer** [NLPchina/elasticsearch-sql#1230]
sql：select count(*) as totle from user where state in(1,8)  union select count(*) as totle from user where state in(2,3,4)  
报错信息：Caused by: java.lang.NullPointerException
	at org.nlpcn.es4sql.Util.clearEmptyPaths(Util.java:222)
	at org.elasticsearch.plugin.nlpcn.UnionExecutor.updateFieldNamesToAlias(UnionExecutor.java:90)
	at org.elasticsearch.plugin.nlpcn.UnionExecutor.fillInternalSearchHits(UnionExecutor.java:55)
	at org.elasticsearch.plugin.nlpcn.UnionExecutor.run(UnionExecutor.java:40)
	at org.elasticsearch.plugin.nlpcn.QueryActionElasticExecutor.executeMultiQueryAction(QueryActionElasticExecutor.java:78)
	at org.elasticsearch.plugin.nlpcn.QueryActionElasticExecutor.executeAnyAction(QueryActionElasticExecutor.java:90)

**Comment by shi-yuan** [comment]
count(*)再union，目前是不支持的

**Comment by AqooDer** [comment]
这个会考虑去实现么？

**Comment by shi-yuan** [comment]
后期会修复的
