### ISSUE TITLE
1.7.4 什么时候支持

### ISSUE THREAD

**Issue by anduo1989** [NLPchina/elasticsearch-sql#136]
1.7.4 什么时候支持

**Comment by eliranmoyal** [comment]
Hey, you can try to install the latest 1.x version (1.4.8), if it is not working I'll install 1.7.4 and will test it tomorrow

**Comment by anduo1989** [comment]
not working 

Exception like this

on ui show:
`
 Error: {"error":"InvalidIndexNameException[[_sql] Invalid index name [_sql], must not start with '_']","status":400}
`

 console is here:
```
org.elasticsearch.indices.InvalidIndexNameException: [_sql] Invalid index name [_sql], must not start with '_'
	at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService.validateIndexName(MetaDataCreateIndexService.java:172)
	at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService.validate(MetaDataCreateIndexService.java:551)
	at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService.access$200(MetaDataCreateIndexService.java:88)
	at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService$2.execute(MetaDataCreateIndexService.java:230)
	at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:374)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:204)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:167)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by ansjsun** [comment]
index name must not start with '_'

**Comment by eliranmoyal** [comment]
Did you restarted the elasticsearch service after installation?

**Comment by anduo1989** [comment]
I restart the service and there is not a index named start with '_'

**Comment by eliranmoyal** [comment]
@anduo1989 
I've just installed elasticsearch 1.7.4 and it worked fine.
After installing 1.4.8 version of the plugin when I didn't restart the service I did get:
`{"error":"InvalidIndexNameException[[_sql] Invalid index name [_sql], must not start with '_']","status":400}`

But after the restart of elasticsearch it worked fine.
