### ISSUE TITLE
currently support only one aggregation at same level？？

### ISSUE THREAD

**Issue by ilevon** [NLPchina/elasticsearch-sql#331]
**version:2.4.1.0**
**the sql：**
select count(*) as pv,count(distinct(userid)) as uv,code,timeandhour
from myindex 
where code='code1' 
and date>='2016-11-01 00:00:00' 
and date<='2016-11-30 00:00:00' 
group by (code),(timeandhour)
**error message:**
Caused by: org.nlpcn.es4sql.jdbc.ObjectResultsExtractException: currently support only one aggregation at same level (Except for numeric metrics)
	at org.nlpcn.es4sql.jdbc.ObjectResultsExtractor.handleAggregations(ObjectResultsExtractor.java:68)
	at org.nlpcn.es4sql.jdbc.ObjectResultsExtractor.extractResults(ObjectResultsExtractor.java:48)
	at com.alibaba.druid.pool.ElasticSearchDruidPooledPreparedStatement.getObjectResult(ElasticSearchDruidPooledPreparedStatement.java:75)
	at com.alibaba.druid.pool.ElasticSearchDruidPooledPreparedStatement.executeQuery(ElasticSearchDruidPooledPreparedStatement.java:47)
	... 6 more

Process finished with exit code 1

**Comment by eliranmoyal** [comment]
When asking for group by (code),(timeandhour)
it means two different on same level aggregations  (multiple aggregations) and not sub-aggregations
This is not supported for now by our jdbc client (as it not standard for rational databases to support this)
if you are looking for sub-aggregations (for each code group by timeandhour)  try group by code,timeandhour
