### ISSUE TITLE
Caused by: NoNodeAvailableException[None of the configured nodes are available --How to solve this problem

### ISSUE THREAD

**Issue by shiyuan417289076** [NLPchina/elasticsearch-sql#390]
I use elasticsearch-sql  testJDBC，

public class JDBCTests {
    @Test
    public void testJDBC() throws Exception {
        Properties properties = new Properties();
          properties.put("url", "jdbc:elasticsearch://11.123.523.777:7300/myindex?cluster.name=mycluster");
        DruidDataSource dds = (DruidDataSource) ElasticSearchDruidDataSourceFactory.createDataSource(properties);
        dds.setInitialSize(1);
        Connection connection = dds.getConnection();
        PreparedStatement ps = connection.prepareStatement("SELECT  *  from  myindex");
        ResultSet resultSet = ps.executeQuery();
        while (resultSet.next()) {
            System.out.println(resultSet.getString("username"));
        }
        ps.close();
        connection.close();
        dds.close();
    }
}
     

java.sql.SQLException: Error
	at com.alibaba.druid.pool.ElasticSearchDruidDataSource.handleConnectionException(ElasticSearchDruidDataSource.java:1109)
	at com.alibaba.druid.pool.DruidPooledConnection.handleException(DruidPooledConnection.java:127)
	at com.alibaba.druid.pool.DruidPooledStatement.checkException(DruidPooledStatement.java:68)
	at com.alibaba.druid.pool.ElasticSearchDruidPooledPreparedStatement.executeQuery(ElasticSearchDruidPooledPreparedStatement.java:62)
	at org.nlpcn.es4sql.JDBCTests.testJDBC(JDBCTests.java:25)
	at org.nlpcn.es4sql.JDBCTests.main(JDBCTests.java:38)
Caused by: NoNodeAvailableException[None of the configured nodes are available: [{#transport#-1}{11.123.523.777}{11.123.523.777:7300}]]
	at org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:290)
	at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:207)
	at org.elasticsearch.client.transport.support.TransportProxyClient.execute(TransportProxyClient.java:55)
	at org.elasticsearch.client.transport.TransportClient.doExecute(TransportClient.java:288)
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:359)
	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:86)
	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:56)
	at org.elasticsearch.action.ActionRequestBuilder.get(ActionRequestBuilder.java:64)
	at org.nlpcn.es4sql.query.SqlElasticSearchRequestBuilder.get(SqlElasticSearchRequestBuilder.java:43)
	at org.elasticsearch.plugin.nlpcn.QueryActionElasticExecutor.executeSearchAction(QueryActionElasticExecutor.java:23)
	at org.elasticsearch.plugin.nlpcn.QueryActionElasticExecutor.executeAnyAction(QueryActionElasticExecutor.java:44)
	at com.alibaba.druid.pool.ElasticSearchDruidPooledPreparedStatement.getObjectResult(ElasticSearchDruidPooledPreparedStatement.java:74)
	at com.alibaba.druid.pool.ElasticSearchDruidPooledPreparedStatement.executeQuery(ElasticSearchDruidPooledPreparedStatement.java:47)
	... 2 more

**Comment by hangum** [comment]
@shiyuan417289076  Did you solve the problem?

**Comment by z56381866** [comment]
@hangum 因为transportclient如果不设置集群名，默认是**elasticsearch**，所以这里要么在客户端设置集群名字，要么在服务端也就是config/elasticsearch.yml文件中修改集群名为**cluster.name: elasticsearch**

**Comment by YeLuoXu** [comment]
why have the es cluster.name been configured,but the problem "Caused by: NoNodeAvailableException[None of the configured nodes are available"  still exists
`
public class JDBCTests {
    @Test
    public void testJDBC() throws Exception {
        Properties properties = new Properties();
        properties.put(PROP_URL, "jdbc:elasticsearch://10.100.8.205:9200/venus_article_rec?cluster.name=es-cluster");
//        properties.put(PROP_CONNECTIONPROPERTIES, "client.transport.ignore_cluster_name=true");
        properties.put(PROP_CONNECTIONPROPERTIES, "cluster.name=es-cluster");
        DruidDataSource dds = (DruidDataSource) ElasticSearchDruidDataSourceFactory.createDataSource(properties);
        Connection connection = dds.getConnection();
        PreparedStatement ps = connection.prepareStatement("SELECT article_no,content from venus_article_rec");
        ResultSet resultSet = ps.executeQuery();
        ResultSetMetaData metaData = resultSet.getMetaData();
        List<String> result = new ArrayList<String>();
        while (resultSet.next()) {
            result.add(resultSet.getString("article_no") + "," + resultSet.getInt("content"));
        }
        ps.close();
        connection.close();
        dds.close();
    }
}
`

**Comment by shi-yuan** [comment]
Are you sure , 9200 ?
