### ISSUE TITLE
Receive exception when using elasticsearch-sql in elasticsearch-site

### ISSUE THREAD

**Issue by jay282** [NLPchina/elasticsearch-sql#391]
Always got exception like below:
org.nlpcn.jcoder.run.java.JavaRunner-44486 INFO  [2017-03-01 12:19:00]  to compile org.nlpcn.elasticsearch.site.sql.SqlApi
2017-03-01 12:19:00.867:WARN:oejs.ServletHandler:qtp471910020-13: /api/SqlApi/execute
java.lang.NullPointerException
        at org.nlpcn.jcoder.run.java.DynamicEngine.javaCodeToClass(DynamicEngine.java:98)
        at org.nlpcn.jcoder.run.java.JavaRunner.compile(JavaRunner.java:76)
        at org.nlpcn.jcoder.run.mvc.ApiUrlMappingImpl.createInvoker(ApiUrlMappingImpl.java:162)
        at org.nlpcn.jcoder.run.mvc.ApiUrlMappingImpl.getOrCreate(ApiUrlMappingImpl.java:142)
        at org.nlpcn.jcoder.run.mvc.ApiUrlMappingImpl.getOrCreate(ApiUrlMappingImpl.java:108)
        at org.nlpcn.jcoder.run.mvc.ApiActionHandler.handle(ApiActionHandler.java:33)
        at org.nlpcn.jcoder.filter.JcoderFilter._doFilter(JcoderFilter.java:80)
        at org.nlpcn.jcoder.filter.JcoderFilter.doFilter(JcoderFilter.java:44)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1650)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:583)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1125)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1059)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.server.Server.handle(Server.java:485)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:290)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:248)
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:606)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:535)
        at java.lang.Thread.run(Unknown Source)

Could u plz tell me how to solve it?

**Comment by ansjsun** [comment]
your es version 5.x pull master
                          2.x pull 2.x branch

you jdk must 1.8

**Comment by ricardoj-br** [comment]
Is jdk 1.8 means Oracle jdk ? Mine is 1.8 but openjdk. Thanks.

**Comment by ricardoj-br** [comment]
Hi there ! Answering my own question : YES it must be Oracle jdk. Now it's working. Thank you all !
