### ISSUE TITLE
执行删除SQL会关闭ES实例

### ISSUE THREAD

**Issue by langke93** [NLPchina/elasticsearch-sql#494]
[2017-08-15T09:34:23,135][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [] fatal error in thread [Thread-61772], exiting
java.lang.NoClassDefFoundError: org/elasticsearch/index/reindex/DeleteByQueryAction
        at org.nlpcn.es4sql.query.ESActionFactory.create(ESActionFactory.java:69) ~[?:?]
        at org.nlpcn.es4sql.SearchDao.explain(SearchDao.java:46) ~[?:?]
        at org.elasticsearch.plugin.nlpcn.RestSqlAction.prepareRequest(RestSqlAction.java:49) ~[?:?]
        at org.elasticsearch.rest.BaseRestHandler.handleRequest(BaseRestHandler.java:66) ~[elasticsearch-5.1.2.jar:5.1.2]
        at org.elasticsearch.rest.RestController.executeHandler(RestController.java:243) ~[elasticsearch-5.1.2.jar:5.1.2]
        at org.elasticsearch.rest.RestController.dispatchRequest(RestController.java:200) ~[elasticsearch-5.1.2.jar:5.1.2]
        at org.elasticsearch.http.HttpServer.dispatchRequest(HttpServer.java:113) ~[elasticsearch-5.1.2.jar:5.1.2]
        at org.elasticsearch.http.netty4.Netty4HttpServerTransport.dispatchRequest(Netty4HttpServerTransport.java:507) ~[?:?]
        at org.elasticsearch.http.netty4.Netty4HttpRequestHandler.channelRead0(Netty4HttpRequestHandler.java:69) ~[?:?]

但是这个了类有在modules/reindex/reindex-5.1.2.jar 里面

**Comment by shi-yuan** [comment]
需要把[reindex-client](https://mvnrepository.com/artifact/org.elasticsearch.plugin/reindex-client)放到es-sql-plugin目录下

**Comment by langke93** [comment]
我es版本5.1.2，把reindex-client-5.1.2.jar放到elasticsearch/plugins/sql目录下，重启后执行
delete play_following wehre id='436_topic_43'
提示错误：
java.lang.UnsupportedOperationException: currently not support delete on elastic 2.x
我看里面代码也是这么写的
https://github.com/NLPchina/elasticsearch-sql/blob/elastic5.1.2/src/main/java/org/elasticsearch/plugin/nlpcn/executors/ElasticDefaultRestExecutor.java
好像最新6.0版本也没有实现这个方法呢

**Comment by shi-yuan** [comment]
不支持删除吧

**Comment by shi-yuan** [comment]
have a look at [执行 delete 语句报错](https://github.com/NLPchina/elasticsearch-sql/issues/347)
