### ISSUE TITLE
issue on 5.5.2

### ISSUE THREAD

**Issue by schwicke** [NLPchina/elasticsearch-sql#505]
Hi, all,
first of all: thanks a lot for the 5.5.2 port of the plugin. I'm still struggling with it though. After installing (on all machines, ES restarted after install) ES loads the module it seems. When trying to access it from the server I get a 'Cannot POST' error. Running directly from the command line like this:
```
curl -XPOST http://localhost:9200/_sql?pretty;sql="select * from indexName limit 10"
```
I get 
```
{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"invalid version format: * FROM INDEXNAME LIMIT 10 HTTP/1.1"}],"type":"illegal_argument_exception","reason":"invalid version format: * FROM INDEXNAME LIMIT 10 HTTP/1.1"},"status":400}
```
(I would get the same if the the plugin was not installed it seems but it is). I have put ES into debug logging mode, and I get this trace (if it helps):
```
[2017-09-05T11:01:52,260][DEBUG][r.suppressed             ] path: /bad-request, params: {}
java.lang.IllegalArgumentException: invalid version format: * FROM INDEXNAME LIMIT 10 HTTP/1.1
        at io.netty.handler.codec.http.HttpVersion.<init>(HttpVersion.java:121) ~[netty-codec-http-4.1.11.Final.jar:4.1.11.Final]
        at io.netty.handler.codec.http.HttpVersion.valueOf(HttpVersion.java:76) ~[netty-codec-http-4.1.11.Final.jar:4.1.11.Final]
        at io.netty.handler.codec.http.HttpRequestDecoder.createMessage(HttpRequestDecoder.java:87) ~[netty-codec-http-4.1.11.Final.jar:4.1.11.Final]
        at io.netty.handler.codec.http.HttpObjectDecoder.decode(HttpObjectDecoder.java:219) ~[netty-codec-http-4.1.11.Final.jar:4.1.11.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489) ~[netty-codec-4.1.11.Final.jar:4.1.11.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428) [netty-codec-4.1.11.Final.jar:4.1.11.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) [netty-codec-4.1.11.Final.jar:4.1.11.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.11.Final.jar:4.1.11.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.11.Final.jar:4.1.11.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.11.Final.jar:4.1.11.Final]
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) [netty-transport-4.1.11.Final.jar:4.1.11.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.11.Final.jar:4.1.11.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.11.Final.jar:4.1.11.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.11.Final.jar:4.1.11.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334) [netty-transport-4.1.11.Final.jar:4.1.11.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.11.Final.jar:4.1.11.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.11.Final.jar:4.1.11.Final]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926) [netty-transport-4.1.11.Final.jar:4.1.11.Final]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134) [netty-transport-4.1.11.Final.jar:4.1.11.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644) [netty-transport-4.1.11.Final.jar:4.1.11.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:544) [netty-transport-4.1.11.Final.jar:4.1.11.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:498) [netty-transport-4.1.11.Final.jar:4.1.11.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458) [netty-transport-4.1.11.Final.jar:4.1.11.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-common-4.1.11.Final.jar:4.1.11.Final]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]
```
Trying to access just _sql, gives
```
curl -XGET http://localhost:9200/_sql
{"error":{"root_cause":[{"type":"string_index_out_of_bounds_exception","reason":"String index out of range: -1"}],"type":"string_index_out_of_bounds_exception","reason":"String index out of range: -1"},"status":500}
```
We are running Centos7.3 with ES 5.5.2. There are no other ES plugins installed. Can anybody reproduce this behavior?

Many thanks in advance.

**Comment by shi-yuan** [comment]
try `curl -H "Content-Type: application/json" -XPOST 'http://localhost:9200/_sql' -d 'SELECT * FROM test LIMIT 10'`

**Comment by schwicke** [comment]
Hi,
indeed, this works. Thanks a lot!
