### ISSUE TITLE
插件安装时候报错：我的es版本是5.5.2，下载的插件是5.5.2.0版本

### ISSUE THREAD

**Issue by leeningli** [NLPchina/elasticsearch-sql#509]
elasticsearch-5.5.2]$ ./bin/elasticsearch-plugin install --verbose file:/wls/wls81/elasticsearch-sql-5.5.2.0.zip 
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/elasticsearch/plugins/PluginCli : Unsupported major.minor version 52.0

**Comment by shi-yuan** [comment]
本地测试，没有问题的
```cmd
D:\elasticsearch\elasticsearch-5.5.2\bin>elasticsearch-plugin install file:///D:/elasticsearch/elasticsearch-sql-5.5.2.0.zip
Plugins directory [D:\elasticsearch\elasticsearch-5.5.2\plugins] does not exist. Creating...
-> Downloading file:///D:/elasticsearch/elasticsearch-sql-5.5.2.0.zip
[=================================================] 100%??
-> Installed sql
```

**Comment by leeningli** [comment]
第一个报错是因为没设置JAVA环境变量，设置之后又报这个错：
[wls81@cnsz141803 plugins]$ ../bin/elasticsearch-plugin install file:/wls/wls81/ELASTICSEARCH5/elasticsearch-5.5.2/plugins/elasticsearch-sql-5.5.2.0.zip 
-> Downloading file:/wls/wls81/ELASTICSEARCH5/elasticsearch-5.5.2/plugins/elasticsearch-sql-5.5.2.0.zip
[=================================================] 100%   
Exception in thread "main" java.lang.IllegalStateException: Could not load plugin descriptor for existing plugin [elasticsearch-sql-5.5.2.0.zip]. Was the plugin built before 2.0?
        at org.elasticsearch.plugins.PluginsService.getPluginBundles(PluginsService.java:334)
        at org.elasticsearch.plugins.InstallPluginCommand.jarHellCheck(InstallPluginCommand.java:518)
        at org.elasticsearch.plugins.InstallPluginCommand.verify(InstallPluginCommand.java:500)
        at org.elasticsearch.plugins.InstallPluginCommand.install(InstallPluginCommand.java:543)
        at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:217)
        at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:201)
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:67)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122)
        at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:69)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122)
        at org.elasticsearch.cli.Command.main(Command.java:88)
        at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:47)
Caused by: java.nio.file.FileSystemException: /wls/wls81/ELASTICSEARCH5/elasticsearch-5.5.2/plugins/elasticsearch-sql-5.5.2.0.zip/plugin-descriptor.properties: Not a directory
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:91)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
        at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
        at java.nio.file.Files.newByteChannel(Files.java:361)
        at java.nio.file.Files.newByteChannel(Files.java:407)
        at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384)
        at java.nio.file.Files.newInputStream(Files.java:152)
        at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:114)
        at org.elasticsearch.plugins.PluginsService.getPluginBundles(PluginsService.java:331)
        ... 11 more

**Comment by leeningli** [comment]
问题解决了。。。解决方法也是醉了

**Comment by liangxinhui** [comment]
> 问题解决了。。。解决方法也是醉了

方法是什么呢？
