### ISSUE TITLE
Does not  support extended_bounds in date_histogram

### ISSUE THREAD

**Issue by milome** [NLPchina/elasticsearch-sql#538]
It's very useful to support extended_bounds to get the full buckets for analysis.
Could you please help?

Thanks a lot.

**Comment by shi-yuan** [comment]
```sql
SELECT online FROM online GROUP BY date_histogram(field='insert_time','interval'='1d','alias'='yourAlias','extended_bounds'='1490278007355:1492693607355')
```

**Comment by vichWei** [comment]
@shi-yuan 请帮忙看看执行出错
sql语句：
select aiops_endpoint.keyword as aiops_endpoint,count(*) as count from aiops_log* where aiops_timestamp >= '2019-01-10T09:25:00.000Z' and aiops_timestamp < '2019-01-13T09:30:00.000Z' group by date_histogram(field='aiops_timestamp','interval'='1d','alias'='aiops_timestamp','min_doc_count'='0','extended_bounds'='1547083500000:1547343000000'),aiops_endpoint


------------
log4j:WARN No appenders could be found for logger (com.alibaba.druid.pool.vendor.MySqlValidConnectionChecker).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console.
java.sql.SQLException: Error
	at com.alibaba.druid.pool.ElasticSearchDruidDataSource.handleConnectionException(ElasticSearchDruidDataSource.java:1109)
	at com.alibaba.druid.pool.DruidPooledConnection.handleException(DruidPooledConnection.java:127)
	at com.alibaba.druid.pool.DruidPooledStatement.checkException(DruidPooledStatement.java:68)
	at com.alibaba.druid.pool.ElasticSearchDruidPooledPreparedStatement.executeQuery(ElasticSearchDruidPooledPreparedStatement.java:61)
	at org.nlpcn.es4sql.Main2.main(Main2.java:90)
Caused by: Failed to execute phase [query], all shards failed; shardFailures {[d0r7oc3TS6eR-sR9A_1_gA][aiops_log][0]: RemoteTransportException[[10.10.100.237][10.10.100.237:9300][indices:data/read/search[phase/query]]]; nested: ElasticsearchParseException[failed to parse date field [1547083500000] with format [yyyy-MM-dd HH:mm:ss]]; nested: IllegalArgumentException[Parse failure at index [9] of [1547083500000]]; }{[d0r7oc3TS6eR-sR9A_1_gA][aiops_log][1]: RemoteTransportException[[10.10.100.237][10.10.100.237:9300][indices:data/read/search[phase/query]]]; nested: ElasticsearchParseException[failed to parse date field [1547083500000] with format [yyyy-MM-dd HH:mm:ss]]; nested: IllegalArgumentException[Parse failure at index [9] of [1547083500000]]; }{[d0r7oc3TS6eR-sR9A_1_gA][aiops_log][2]: RemoteTransportException[[10.10.100.237][10.10.100.237:9300][indices:data/read/search[phase/query]]]; nested: ElasticsearchParseException[failed to parse date field [1547083500000] with format [yyyy-MM-dd HH:mm:ss]]; nested: IllegalArgumentException[Parse failure at index [9] of [1547083500000]]; }{[EGg0HOPrTByzU9egjW_fnw][aiops_log][3]: RemoteTransportException[[10.10.100.236][10.10.100.236:9300][indices:data/read/search[phase/query]]]; nested: ElasticsearchParseException[failed to parse date field [1547083500000] with format [yyyy-MM-dd HH:mm:ss]]; nested: IllegalArgumentException[Parse failure at index [9] of [1547083500000]]; }{[d0r7oc3TS6eR-sR9A_1_gA][aiops_log][4]: RemoteTransportException[[10.10.100.237][10.10.100.237:9300][indices:data/read/search[phase/query]]]; nested: ElasticsearchParseException[failed to parse date field [1547083500000] with format [yyyy-MM-dd HH:mm:ss]]; nested: IllegalArgumentException[Parse failure at index [9] of [1547083500000]]; }
	at org.elasticsearch.action.search.AbstractSearchAsyncAction.onInitialPhaseResult(AbstractSearchAsyncAction.java:223)
	at org.elasticsearch.action.search.AbstractSearchAsyncAction.access$100(AbstractSearchAsyncAction.java:58)
	at org.elasticsearch.action.search.AbstractSearchAsyncAction$1.onFailure(AbstractSearchAsyncAction.java:148)
	at org.elasticsearch.action.ActionListenerResponseHandler.handleException(ActionListenerResponseHandler.java:51)
	at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:1032)
	at org.elasticsearch.transport.TcpTransport.lambda$handleException$17(TcpTransport.java:1411)
	at org.elasticsearch.common.util.concurrent.EsExecutors$1.execute(EsExecutors.java:109)
	at org.elasticsearch.transport.TcpTransport.handleException(TcpTransport.java:1409)
	at org.elasticsearch.transport.TcpTransport.handlerResponseError(TcpTransport.java:1401)
	at org.elasticsearch.transport.TcpTransport.messageReceived(TcpTransport.java:1345)
	at org.elasticsearch.transport.netty4.Netty4MessageChannelHandler.channelRead(Netty4MessageChannelHandler.java:74)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:280)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:396)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:129)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:642)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:527)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:481)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:441)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Thread.java:745)
Caused by: RemoteTransportException[[10.10.100.237][10.10.100.237:9300][indices:data/read/search[phase/query]]]; nested: ElasticsearchParseException[failed to parse date field [1547083500000] with format [yyyy-MM-dd HH:mm:ss]]; nested: IllegalArgumentException[Parse failure at index [9] of [1547083500000]];
Caused by: ElasticsearchParseException[failed to parse date field [1547083500000] with format [yyyy-MM-dd HH:mm:ss]]; nested: IllegalArgumentException[Parse failure at index [9] of [1547083500000]];
	at org.elasticsearch.common.joda.DateMathParser.parseDateTime(DateMathParser.java:213)
	at org.elasticsearch.common.joda.DateMathParser.parse(DateMathParser.java:66)
	at org.elasticsearch.search.DocValueFormat$DateTime.parseLong(DocValueFormat.java:170)
	at org.elasticsearch.search.aggregations.bucket.histogram.ExtendedBounds.parseAndValidate(ExtendedBounds.java:156)
	at org.elasticsearch.search.aggregations.bucket.histogram.DateHistogramAggregationBuilder.innerBuild(DateHistogramAggregationBuilder.java:329)
	at org.elasticsearch.search.aggregations.support.ValuesSourceAggregationBuilder.doBuild(ValuesSourceAggregationBuilder.java:291)
	at org.elasticsearch.search.aggregations.support.ValuesSourceAggregationBuilder.doBuild(ValuesSourceAggregationBuilder.java:39)
	at org.elasticsearch.search.aggregations.AbstractAggregationBuilder.build(AbstractAggregationBuilder.java:126)
	at org.elasticsearch.search.aggregations.AggregatorFactories$Builder.build(AggregatorFactories.java:333)
	at org.elasticsearch.search.SearchService.parseSource(SearchService.java:637)
	at org.elasticsearch.search.SearchService.createContext(SearchService.java:468)
	at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:444)
	at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:252)
	at org.elasticsearch.action.search.SearchTransportService$6.messageReceived(SearchTransportService.java:331)
	at org.elasticsearch.action.search.SearchTransportService$6.messageReceived(SearchTransportService.java:328)
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:69)
	at org.elasticsearch.transport.TcpTransport$RequestHandler.doRun(TcpTransport.java:1488)
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:638)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: Parse failure at index [9] of [1547083500000]
	at org.elasticsearch.common.joda.DateMathParser.parseDateTime(DateMathParser.java:207)
	... 21 more
{"msg":"FAILURE","code":-1,"dataList":[]}

**Comment by shi-yuan** [comment]
https://github.com/NLPchina/elasticsearch-sql/issues/855
