### ISSUE TITLE
error installing 5.6.3 SQL plugin

### ISSUE THREAD

**Issue by kosckosc** [NLPchina/elasticsearch-sql#548]
Hi

I installed 5.6.3 Elasticsearchh on my linux box:

```
{
"name": "virtual1",
"cluster_name": "Virtual1",
"cluster_uuid": "Hdh18FKPTz--J-N29b0tsg",
"version": {
"number": "5.6.3",
"build_hash": "1a2f265",
"build_date": "2017-10-06T20:33:39.012Z",
"build_snapshot": false,
"lucene_version": "6.6.1"
},
"tagline": "You Know, for Search"
}
```

after installing SQL plugin with:

```
/usr/share/elasticsearch#  ./bin/elasticsearch-plugin install https://github.com/NLPchina/elasticsearch-sql/releases/download/5.6.3.0/elasticsearch-sql-5.6.3.0.zip
```

and I got error:

```
Exception in thread "main" java.lang.IllegalArgumentException: plugin [sql] is incompatible with version [5.6.4]; was designed for version [5.6.3]
        at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:146)
        at org.elasticsearch.plugins.InstallPluginCommand.verify(InstallPluginCommand.java:501)
        at org.elasticsearch.plugins.InstallPluginCommand.install(InstallPluginCommand.java:570)
        at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:218)
        at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:202)
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:70)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:134)
        at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:69)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:134)
        at org.elasticsearch.cli.Command.main(Command.java:90)
        at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:47)
```

after installing node (plugin failed)

```
cd site-server
npm install express --save
node node-server.js
```

plugin starts at 8080 port but is unable to connect to elasticsearch 

![sql](https://user-images.githubusercontent.com/3097678/32776751-d9f138fc-c933-11e7-8fd1-2f677cbf5683.png)

any suggestions ?

**Comment by shi-yuan** [comment]
本机测试，没问题的

![_20171120100009](https://user-images.githubusercontent.com/8057153/32998906-bd0eb2d2-cdd9-11e7-89ba-8212519b83cb.png)

![_20171120100030](https://user-images.githubusercontent.com/8057153/32998910-c05a5f9a-cdd9-11e7-98bd-6d526f15cb14.png)

**Comment by kosckosc** [comment]
After installing 5.6.4. ES, plugin 5.6.4. works fine but 
server installed od port 8080 still have problem,


```
cd site-server
npm install express --save
node node-server.js
```

**Comment by davidpelfree** [comment]
Maybe CORS issue. Run these as root:

echo 'http.cors.enabled: true' >> /etc/elasticsearch/elasticsearch.yml
echo 'http.cors.allow-origin: http://localhost:8080' >> /etc/elasticsearch/elasticsearch.yml

Read more here: https://www.elastic.co/guide/en/elasticsearch/reference/6.2/modules-http.html
