### ISSUE TITLE
连接超时

### ISSUE THREAD

**Issue by sunpeihao** [NLPchina/elasticsearch-sql#572]
[2017-12-22T16:46:48,524][WARN ][o.e.t.n.Netty4Transport  ] [sjyjetl] exception caught on transport layer [[id: 0x64b2977e, L:/192.168.0.45:9300 - R:/124.127.206.77:18828]], closing connection
java.io.IOException: 连接超时
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[?:?]
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~[?:?]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[?:?]
	at sun.nio.ch.IOUtil.read(IOUtil.java:197) ~[?:?]
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:375) ~[?:?]
	at io.netty.buffer.PooledHeapByteBuf.setBytes(PooledHeapByteBuf.java:261) ~[netty-buffer-4.1.13.Final.jar:4.1.13.Final]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1100) ~[netty-buffer-4.1.13.Final.jar:4.1.13.Final]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:372) ~[netty-transport-4.1.13.Final.jar:4.1.13.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:123) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:544) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:498) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-common-4.1.13.Final.jar:4.1.13.Final]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_11]

**Comment by shi-yuan** [comment]
[connection closing/timeout issue maybe related to client node](https://github.com/elastic/elasticsearch/issues/21326)

**Comment by vichWei** [comment]
@shi-yuan 您好！我利用es jdbc打成jar包在spark环境里运行，有一个netty-all-4.1.x.Final.jar或netty-transport-4.1.xx.Final.jar的包冲突，因为spark的jar包是用netty-all-4.0.x.Final.jar
我的问题是：在es sql里哪里依赖了netty-all-4.1.x.Final.jar和netty-transport-4.1.xx.Final.jar，在pom.xml里没找到
报错在执行以下第二行代码时发生：
System.out.println("-----------query es sql:" + sql);
resultSet = ps.executeQuery();
System.out.println("-----------query resultSet--------");

报错如下：
-----------query es sql:select aiops_endpoint.keyword as aiops_endpoint,count(*) as value from swp_fmt_log_nginx_cn_* group by date_histogram(field='aiops_timestamp','interval'='1d','alias'='aiops_timestamp'),aiops_endpoint
java.lang.NoSuchMethodError: io.netty.bootstrap.Bootstrap.config()Lio/netty/bootstrap/BootstrapConfig;
	at org.elasticsearch.transport.netty4.Netty4Transport.lambda$stopInternal$4(Netty4Transport.java:460)
	at org.apache.lucene.util.IOUtils.close(IOUtils.java:89)
	at org.elasticsearch.common.lease.Releasables.close(Releasables.java:36)
	at org.elasticsearch.common.lease.Releasables.close(Releasables.java:46)
	at org.elasticsearch.common.lease.Releasables.close(Releasables.java:51)
	at org.elasticsearch.transport.netty4.Netty4Transport.stopInternal(Netty4Transport.java:443)
	at org.elasticsearch.transport.TcpTransport.lambda$doStop$4(TcpTransport.java:936)
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:569)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

期待您的回复，谢谢：）

**Comment by shi-yuan** [comment]
执行mvn dependency:tree，看看哪儿有依赖，然后exclude
