### ISSUE TITLE
6.2.1 Error on installation

### ISSUE THREAD

**Issue by dexion** [NLPchina/elasticsearch-sql#610]
```bash
user@elk:/usr/share/elasticsearch$ sudo ES_JAVA_OPTS="-Dhttp.proxyHost=localhost -Dhttp.proxyPort=3128 -Dhttps.proxyHost=localhost -Dhttps.proxyPort=3128" ./bin/elasticsearch-plugin install https://github.com/NLPchina/elasticsearch-sql/releases/download/6.2.1.0/elasticsearch-sql-6.2.1.0.zip
-> Downloading https://github.com/NLPchina/elasticsearch-sql/releases/download/6.2.1.0/elasticsearch-sql-6.2.1.0.zip
[=================================================] 100%  
Exception in thread "main" java.lang.IllegalArgumentException: Unknown properties in plugin descriptor: [jvm, site]
        at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:297)
        at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:184)
        at org.elasticsearch.plugins.InstallPluginCommand.loadPluginInfo(InstallPluginCommand.java:571)
        at org.elasticsearch.plugins.InstallPluginCommand.installPlugin(InstallPluginCommand.java:707)
        at org.elasticsearch.plugins.InstallPluginCommand.install(InstallPluginCommand.java:623)
        at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:223)
        at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:212)
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)
        at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:75)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)
        at org.elasticsearch.cli.Command.main(Command.java:90)
        at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:48)
```

**Comment by smsmithee** [comment]
I also get that error when trying to upgrade/install 6.2.1.0

**Comment by hjxhjh** [comment]
me too
[=================================================] 100%
Exception in thread "main" java.lang.IllegalArgumentException: Unknown properties in plugin descriptor: [jvm, site]
	at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:297)
	at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:184)
	at org.elasticsearch.plugins.InstallPluginCommand.loadPluginInfo(InstallPluginCommand.java:571)
	at org.elasticsearch.plugins.InstallPluginCommand.installPlugin(InstallPluginCommand.java:707)
	at org.elasticsearch.plugins.InstallPluginCommand.install(InstallPluginCommand.java:623)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:223)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:212)
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)
	at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:75)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)
	at org.elasticsearch.cli.Command.main(Command.java:90)
	at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:48)

**Comment by hjxhjh** [comment]
解压后直接放到ES_HOME/plugins/sql 下面， 同时将plugin-descriptor.properties 配置文件里面 jvm 和 site 参数去除就可以了。

**Comment by veronesip** [comment]
I have the same errore:
[root@eladevsolelbr01vm ~]#  /usr/share/elasticsearch/bin/elasticsearch-plugin install file:///elasticsearch-sql-6.2.1.0.zip
-> Downloading file:///home/paolo.veronesi/elasticsearch-sql-6.2.1.0.zip
[=================================================] 100%  
Exception in thread "main" java.lang.IllegalArgumentException: Unknown properties in plugin descriptor: [jvm, site]
        at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:297)
        at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:184)
        at org.elasticsearch.plugins.InstallPluginCommand.loadPluginInfo(InstallPluginCommand.java:571)
        at org.elasticsearch.plugins.InstallPluginCommand.installPlugin(InstallPluginCommand.java:707)
        at org.elasticsearch.plugins.InstallPluginCommand.install(InstallPluginCommand.java:623)
        at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:223)
        at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:212)
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)
        at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:75)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)
        at org.elasticsearch.cli.Command.main(Command.java:90)
        at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:48)

**Comment by veronesip** [comment]
Hello, it seems that https://github.com/NLPchina/elasticsearch-sql/releases/download/6.2.1.0/elasticsearch-sql-6.2.1.0.zip has not been update, has it?

**Comment by shi-yuan** [comment]
:point_right:  [elasticsearch-sql-6.2.1.1.zip](https://github.com/NLPchina/elasticsearch-sql/files/1743863/elasticsearch-sql-6.2.1.1.zip)

**Comment by lccbiluox2** [comment]
我也遇到这个问题了，而且mvn package编译也出问题
D:\elasticsearch\elasticsearch-6.2.0\bin>elasticsearch-plugin install https://github.com/NLPchina/elasticsearch-sql/releases/download/6.2.0.0/elasticsearch-sql-6.2.0.0.zip
-> Downloading https://github.com/NLPchina/elasticsearch-sql/releases/download/6.2.0.0/elasticsearch-sql-6.2.0.0.zip
[=================================================] 100%??
Exception in thread "main" java.lang.IllegalArgumentException: Unknown properties in plugin descriptor: [jvm, site]
        at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:284)
        at org.elasticsearch.plugins.InstallPluginCommand.loadPluginInfo(InstallPluginCommand.java:571)
        at org.elasticsearch.plugins.InstallPluginCommand.installPlugin(InstallPluginCommand.java:707)
        at org.elasticsearch.plugins.InstallPluginCommand.install(InstallPluginCommand.java:623)
        at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:223)
        at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:212)
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)
        at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:75)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)
        at org.elasticsearch.cli.Command.main(Command.java:90)
        at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:48)

D:\elasticsearch\elasticsearch-6.2.0\bin>


D:\elasticsearch\elasticsearch-sql-elastic6.2.1>mvn -X package
[INFO] ------------------------------------------------------------------------
[ERROR] 14432
java.lang.ArrayIndexOutOfBoundsException: 14432
        at org.codehaus.plexus.util.xml.pull.MXParser.parsePI(MXParser.java:2502)
        at org.codehaus.plexus.util.xml.pull.MXParser.parseEpilog(MXParser.java:1604)
        at org.codehaus.plexus.util.xml.pull.MXParser.nextImpl(MXParser.java:1434)
        at org.codehaus.plexus.util.xml.pull.MXParser.next(MXParser.java:1131)
        at org.apache.maven.model.io.xpp3.MavenXpp3Reader.read(MavenXpp3Reader.java:3856)
        at org.apache.maven.model.io.xpp3.MavenXpp3Reader.read(MavenXpp3Reader.java:595)

**Comment by shi-yuan** [comment]
把这两个文件的两个配置删除：
![1](https://user-images.githubusercontent.com/8057153/36879903-e8a0131a-1e00-11e8-8592-48b3d521ad7d.png)

然后重新打包：`mvn package -DskipTests`
