### ISSUE TITLE
RANGE COUNT PROBLEAM

### ISSUE THREAD

**Issue by xiangHannibal** [NLPchina/elasticsearch-sql#619]
SELECT COUNT(age) FROM bank GROUP BY range(age, 20,25,30,35,40)

这个我如果想的是 <20(小于),20~30,30~40,>40(大于40)的该怎么写呢

**Comment by xiangHannibal** [comment]
SELECT COUNT(speed1) FROM table GROUP BY range(speed1, -Infinity, 20,30,40,50, Infinity)查询失败。
java.lang.NullPointerException: null
	at org.nlpcn.es4sql.domain.KVValue.toString(KVValue.java:21)
	at org.nlpcn.es4sql.Util.joiner(Util.java:31)
	at org.nlpcn.es4sql.domain.MethodField.toString(MethodField.java:52)
	at org.nlpcn.es4sql.domain.MethodField.<init>(MethodField.java:29)
	at org.nlpcn.es4sql.parse.FieldMaker.makeMethodField(FieldMaker.java:303)
	at org.nlpcn.es4sql.parse.FieldMaker.makeField(FieldMaker.java:54)
	at org.nlpcn.es4sql.parse.SqlParser.convertExprsToFields(SqlParser.java:132)
	at org.nlpcn.es4sql.parse.SqlParser.findGroupBy(SqlParser.java:124)
	at org.nlpcn.es4sql.parse.SqlParser.parseSelect(SqlParser.java:60)
	at org.nlpcn.es4sql.parse.SqlParser.parseSelect(SqlParser.java:35)
	at org.nlpcn.es4sql.query.ESActionFactory.create(ESActionFactory.java:61)
	at org.nlpcn.es4sql.SearchDao.explain(SearchDao.java:46)
	at com.dfssi.motorcade.es.SearchCenter.searchSQL(SearchCenter.java:47)
	at com.dfssi.motorcade.es.SearchCenter.main(SearchCenter.java:81)

**Comment by xiangHannibal** [comment]
这个好像不行啊
SELECT COUNT(speed1) FROM table GROUP BY range(speed1, '-Infinity',20,30,40,50,'Infinity')查询失败。
java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Number
	at org.nlpcn.es4sql.Util.KV2DoubleArr(Util.java:142)
	at org.nlpcn.es4sql.query.maker.AggMaker.rangeBuilder(AggMaker.java:551)
	at org.nlpcn.es4sql.query.maker.AggMaker.makeRangeGroup(AggMaker.java:206)
	at org.nlpcn.es4sql.query.maker.AggMaker.makeGroupAgg(AggMaker.java:67)
	at org.nlpcn.es4sql.query.AggregationQueryAction.getGroupAgg(AggregationQueryAction.java:214)
	at org.nlpcn.es4sql.query.AggregationQueryAction.explain(AggregationQueryAction.java:63)
	at org.nlpcn.es4sql.query.AggregationQueryAction.explain(AggregationQueryAction.java:37)
	at com.dfssi.motorcade.es.SearchCenter.searchSQL(SearchCenter.java:47)
	at com.dfssi.motorcade.es.SearchCenter.main(SearchCenter.java:81)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)

**Comment by shi-yuan** [comment]
更新在了master分支上
