### ISSUE TITLE
java.sql.SQLException: Error PreparedStatement setObject

### ISSUE THREAD

**Issue by phypor** [NLPchina/elasticsearch-sql#671]
DruidDataSource dds = (DruidDataSource)ElasticSearchDruidDataSourceFactory.createDataSource(properties);
            Connection connection = dds.getConnection();
            PreparedStatement ps = connection.prepareStatement(sql);
            for(int i=0;i!=params.length;++i){
                System.out.println(i+1+" "+params[i]);
                ps.setObject(i+1,params[i]);
            } 
              resultSet = ps.executeQuery();

java.sql.SQLException: Error
	at com.alibaba.druid.pool.DruidPooledConnection.handleException(DruidPooledConnection.java:134)
	at com.alibaba.druid.pool.DruidPooledStatement.checkException(DruidPooledStatement.java:68)
	at com.alibaba.druid.pool.DruidPooledResultSet.checkException(DruidPooledResultSet.java:55)
	at com.alibaba.druid.pool.DruidPooledResultSet.getString(DruidPooledResultSet.java:113)

**Comment by shi-yuan** [comment]
Sorry, not supported!
