### ISSUE TITLE
5.6.3 版本 jdbc连接时 卡住问题

### ISSUE THREAD

**Issue by zhenglu696** [NLPchina/elasticsearch-sql#676]
自己打包后，将包引入到项目中的lib下，运行jdbc的代码查查询，卡在了connenction上。直接在git上check 出来的test代码里面可以运行，请问这是打包问题，还是需要修改哪些东西？

**Comment by zhenglu696** [comment]
@shi-yuan 辛苦看一下？

**Comment by shi-yuan** [comment]
没报错是吗？方便看一下工程吗？

**Comment by bolodanta** [comment]
Connection connection = dds.getConnection(1000L);
不报错卡住是因为没有设置timeout参数，但设置了就会报下面错误@shi-yuan：

com.alibaba.druid.pool.GetConnectionTimeoutException: wait millis 1001, active 0, maxActive 8
	at com.alibaba.druid.pool.ElasticSearchDruidDataSource.getConnectionInternal(ElasticSearchDruidDataSource.java:1053)
	at com.alibaba.druid.pool.ElasticSearchDruidDataSource.getConnectionDirect(ElasticSearchDruidDataSource.java:917)
	at com.alibaba.druid.pool.ElasticSearchDruidDataSource.getConnection(ElasticSearchDruidDataSource.java:898)
	at com.vansight.api.ESSqlJDBCTests.testJDBC(ESSqlJDBCTests.java:24)
	at com.vansight.api.EsSqlTest.main(EsSqlTest.java:9)

**Comment by shi-yuan** [comment]
和设置这个没关系的。配置访问权限了吗？可以试试TransportClient能不能正常访问

**Comment by ighack** [comment]
我也遇到这个问题就是停在了Connection connection = dds.getConnection();
按照shi-yuan说的用TransportClient试一下。是没问题
试完了在去dds.getConnection();一正常了，不知道是个什么原理

**Comment by shi-yuan** [comment]
应该是连接的时候卡住了，一直连不上
