### ISSUE TITLE
XContentBuilder conflict

### ISSUE THREAD

**Issue by Jacky0312** [NLPchina/elasticsearch-sql#785]
I'm use x-pack-sql-jdbc-6.4.2.jar connct to elasticsearch for sql query.
But when I started the UT, reported the following error:
```
Caused by: java.lang.NoSuchMethodError: org.elasticsearch.common.xcontent.XContentBuilder.string()Ljava/lang/String;
	at org.elasticsearch.common.settings.Setting.arrayToParsableString(Setting.java:1173)
	at org.elasticsearch.common.settings.Setting.access$600(Setting.java:83)
	at org.elasticsearch.common.settings.Setting$ListSetting.lambda$new$0(Setting.java:872)
	at org.elasticsearch.common.settings.Setting.<init>(Setting.java:130)
	at org.elasticsearch.common.settings.Setting.<init>(Setting.java:172)
	at org.elasticsearch.common.settings.Setting.<init>(Setting.java:158)
	at org.elasticsearch.common.settings.Setting$ListSetting.<init>(Setting.java:872)
	at org.elasticsearch.common.settings.Setting$ListSetting.<init>(Setting.java:867)
	at org.elasticsearch.common.settings.Setting.listSetting(Setting.java:1142)
	at org.elasticsearch.common.settings.Setting.listSetting(Setting.java:1125)
	at org.elasticsearch.transport.TcpTransport.<clinit>(TcpTransport.java:128)
	at org.elasticsearch.client.transport.TransportClient.newPluginService(TransportClient.java:100)
```

I checked the code, it seems that elasticsearch conflicts with the XContentBuilder class in x-pack.
elasticsearch version: 6.2.2
x-pack-sql-jdbc version: 6.4.2

**Comment by shi-yuan** [comment]
Version inconsistency？

**Comment by Jacky0312** [comment]
Ignore, not issue.
