### ISSUE TITLE
6.2.2版本，es集群用了x-pack认证，连接的时候出了如下问题，请问还需要其他的什么配置

### ISSUE THREAD

**Issue by wluoer** [NLPchina/elasticsearch-sql#795]
public static void main(String [] args) throws Exception{
        Properties properties = new Properties();
        properties.put(PROP_URL, "jdbc:elasticsearch://192.168.204.128:9300");
        properties.put(PROP_CONNECTIONPROPERTIES, "client.transport.ignore_cluster_name=true;xpack.security.user=elastic:test123456");
        DruidDataSource dds = (DruidDataSource) ElasticSearchDruidDataSourceFactory.createDataSource(properties);
        Connection connection = dds.getConnection();
        PreparedStatement ps = connection.prepareStatement("select * from indexName limit 10");
        ResultSet resultSet = ps.executeQuery();
        resultSet.next();
        while (resultSet.next()) {
            String string_value = resultSet.getString(1);
            String int_value = resultSet.getString(2);
            System.out.println("int_value : " + int_value + "    "+"string_value : " + string_value );
//            System.out.println(resultSet.getInt("sex"));
        }
        ps.close();
        connection.close();
        dds.close();
    }

2018-11-15 11:43:58.871 luoer  INFO [Druid-ConnectionPool-Create-1211888640] o.e.c.t.TransportClientNodesService : [] failed to get node info for {#transport#-1}{oZstjb_aR76LHlcxRJGQUA}{192.168.204.128}{192.168.204.128:9300}, disconnecting...
org.elasticsearch.transport.RemoteTransportException: [DPM7lao][192.168.204.128:9300][cluster:monitor/nodes/liveness]
Caused by: org.elasticsearch.ElasticsearchSecurityException: missing authentication token for action [cluster:monitor/nodes/liveness]
	at org.elasticsearch.xpack.core.security.support.Exceptions.authenticationError(Exceptions.java:36) 
	at org.elasticsearch.xpack.core.security.authc.DefaultAuthenticationFailureHandler.missingToken(DefaultAuthenticationFailureHandler.java:74) 
	at org.elasticsearch.xpack.security.authc.AuthenticationService$AuditableTransportRequest.anonymousAccessDenied(AuthenticationService.java:535) 
	at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.lambda$handleNullToken$17(AuthenticationService.java:347) 
	at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.handleNullToken(AuthenticationService.java:352) 
	at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.consumeToken(AuthenticationService.java:267) 
	at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.lambda$extractToken$7(AuthenticationService.java:238) 
	at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.extractToken(AuthenticationService.java:256) 
	at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.lambda$authenticateAsync$0(AuthenticationService.java:190) 
	at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:60) 
	at org.elasticsearch.xpack.security.authc.TokenService.getAndValidateToken(TokenService.java:313) 
	at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.lambda$authenticateAsync$2(AuthenticationService.java:186) 
	at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.lambda$lookForExistingAuthentication$4(AuthenticationService.java:217) 
	at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.lookForExistingAuthentication(AuthenticationService.java:228) 
	at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.authenticateAsync(AuthenticationService.java:182) 
	at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.access$000(AuthenticationService.java:143) 
	at org.elasticsearch.xpack.security.authc.AuthenticationService.authenticate(AuthenticationService.java:113) 
	at org.elasticsearch.xpack.security.transport.ServerTransportFilter$NodeProfile.inbound(ServerTransportFilter.java:142) 
	at org.elasticsearch.xpack.security.transport.SecurityServerTransportInterceptor$ProfileSecuredRequestHandler.messageReceived(SecurityServerTransportInterceptor.java:314) 
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:66) 
	at org.elasticsearch.transport.TcpTransport$RequestHandler.doRun(TcpTransport.java:1555) 
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) 
	at org.elasticsearch.common.util.concurrent.EsExecutors$1.execute(EsExecutors.java:135) 
	at org.elasticsearch.transport.TcpTransport.handleRequest(TcpTransport.java:1512) 
	at org.elasticsearch.transport.TcpTransport.messageReceived(TcpTransport.java:1382) 
	at org.elasticsearch.transport.netty4.Netty4MessageChannelHandler.channelRead(Netty4MessageChannelHandler.java:64) 
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) 
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) 
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) 
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) 
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:297) 
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:413) 
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) 
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) 
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) 
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) 
	at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:241) 
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) 
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) 
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) 
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359) 
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) 
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) 
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935) 
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134) 
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645) 
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:545) 
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:499) 
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459) 
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) 
	at java.lang.Thread.run(Thread.java:748) 
Exception in thread "main" java.sql.SQLException: Error
	at com.alibaba.druid.pool.ElasticSearchDruidDataSource.handleConnectionException(ElasticSearchDruidDataSource.java:1109)
	at com.alibaba.druid.pool.DruidPooledConnection.handleException(DruidPooledConnection.java:127)
	at com.alibaba.druid.pool.DruidPooledStatement.checkException(DruidPooledStatement.java:68)
	at com.alibaba.druid.pool.ElasticSearchDruidPooledPreparedStatement.executeQuery(ElasticSearchDruidPooledPreparedStatement.java:61)
	at com.pinduoduo.bigdata.force.es.api.httpController.ts.main(ts.java:39)
Caused by: NoNodeAvailableException[None of the configured nodes are available: [{#transport#-1}{oZstjb_aR76LHlcxRJGQUA}{192.168.204.128}{192.168.204.128:9300}]]
	at org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:347)
	at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:245)
	at org.elasticsearch.client.transport.TransportProxyClient.execute(TransportProxyClient.java:59)
	at org.elasticsearch.client.transport.TransportClient.doExecute(TransportClient.java:363)
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:408)
	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:80)
	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:54)
	at org.elasticsearch.action.ActionRequestBuilder.get(ActionRequestBuilder.java:62)
	at org.nlpcn.es4sql.query.SqlElasticSearchRequestBuilder.get(SqlElasticSearchRequestBuilder.java:36)
	at org.elasticsearch.plugin.nlpcn.QueryActionElasticExecutor.executeSearchAction(QueryActionElasticExecutor.java:25)
	at org.elasticsearch.plugin.nlpcn.QueryActionElasticExecutor.executeAnyAction(QueryActionElasticExecutor.java:53)
	at com.alibaba.druid.pool.ElasticSearchDruidPooledPreparedStatement.getObjectResult(ElasticSearchDruidPooledPreparedStatement.java:73)
	at com.alibaba.druid.pool.ElasticSearchDruidPooledPreparedStatement.executeQuery(ElasticSearchDruidPooledPreparedStatement.java:46)
	... 1 more

**Comment by shi-yuan** [comment]
6.2.2版本不支持的，可以参考最新分支上com.alibaba.druid.pool这个包下的代码

**Comment by shi-yuan** [comment]
最新分支上是支持的

**Comment by wluoer** [comment]
好的，感谢

**Comment by wkjun** [comment]
6.4.0上支持吗？最低哪个版本已经支持呢？

**Comment by shi-yuan** [comment]
如果是6.4.0的话，建议直接clone最新分支master的代码，然后修改pom.xml里的elasticsearch.version的版本为6.4.0，之后本地打包即可

**Comment by wkjun** [comment]
恩恩，借用了您提到的浏览器chrome插件方式也实现了，填完链接后，需要刷新下页面，出来验证框即可验证。[https://upload.cc/i1/2019/01/02/LzN5JG.png
](url)

**Comment by w4n9H** [comment]
5.4.1的包支持xpack吗，我用本地es不带xpack的可用，用线上测试es带xpack的就不行，报错是NoNodeAvailableException[None of the configured nodes are available，
