### ISSUE TITLE
集成到spring boot出错

### ISSUE THREAD

**Issue by ighack** [NLPchina/elasticsearch-sql#841]
spring boot 1.5.18.RELEASE
用了cloud
pom.xml中添加了
`<dependency>
            <groupId>org.elasticsearch.client</groupId>
            <artifactId>transport</artifactId>
            <version>5.4.1</version>
        </dependency>
`
我直接在IDEA中添加了你项目中的
elasticsearch-sql-5.4.1.0.jar
druid.jar

> 2018-12-28 14:05:48.406  WARN 4880 --- [nio-8080-exec-1] c.a.d.p.v.MySqlValidConnectionChecker    : Cannot resolve com.mysq.jdbc.Connection.ping method.  Will use 'SELECT 1' instead.
> 
> java.lang.NullPointerException: null
> 	at com.alibaba.druid.pool.vendor.MySqlValidConnectionChecker.<init>(MySqlValidConnectionChecker.java:48) ~[druid.jar:1.0.15]
> 	at com.alibaba.druid.pool.ElasticSearchDruidDataSource.initValidConnectionChecker(ElasticSearchDruidDataSource.java:880) [elasticsearch-sql-5.4.1.0.jar:na]
> 	at com.alibaba.druid.pool.ElasticSearchDruidDataSource.init(ElasticSearchDruidDataSource.java:546) [elasticsearch-sql-5.4.1.0.jar:na]
> 	at com.alibaba.druid.pool.ElasticSearchDruidDataSource.getConnection(ElasticSearchDruidDataSource.java:897) [elasticsearch-sql-5.4.1.0.jar:na]
> 	at com.alibaba.druid.pool.ElasticSearchDruidDataSource.getConnection(ElasticSearchDruidDataSource.java:893) [elasticsearch-sql-5.4.1.0.jar:na]
> 	at com.joint.jztesjdbc.common.EsJdbc.runSQL(EsJdbc.java:33) [classes/:na]
> 	at com.joint.jztesjdbc.controller.EsSearchController.search(EsSearchController.java:22) [classes/:na]
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_121]
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_121]
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_121]
> 	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_121]
> 	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205) [spring-web-4.3.21.RELEASE.jar:4.3.21.RELEASE]
> 	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133) [spring-web-4.3.21.RELEASE.jar:4.3.21.RELEASE]
> 	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97) [spring-webmvc-4.3.21.RELEASE.jar:4.3.21.RELEASE]
> 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:849) [spring-webmvc-4.3.21.RELEASE.jar:4.3.21.RELEASE]
> 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:760) [spring-webmvc-4.3.21.RELEASE.jar:4.3.21.RELEASE]
> 	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85) [spring-webmvc-4.3.21.RELEASE.jar:4.3.21.RELEASE]
> 	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967) [spring-webmvc-4.3.21.RELEASE.jar:4.3.21.RELEASE]
> 	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901) [spring-webmvc-4.3.21.RELEASE.jar:4.3.21.RELEASE]
> 	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970) [spring-webmvc-4.3.21.RELEASE.jar:4.3.21.RELEASE]
> 	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872) [spring-webmvc-4.3.21.RELEASE.jar:4.3.21.RELEASE]
> 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:661) [tomcat-embed-core-8.5.35.jar:8.5.35]
> 	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846) [spring-webmvc-4.3.21.RELEASE.jar:4.3.21.RELEASE]
> 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742) [tomcat-embed-core-8.5.35.jar:8.5.35]
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [tomcat-embed-core-8.5.35.jar:8.5.35]
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.35.jar:8.5.35]
> 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat-embed-websocket-8.5.35.jar:8.5.35]
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.35.jar:8.5.35]
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.35.jar:8.5.35]
> 	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99) [spring-web-4.3.21.RELEASE.jar:4.3.21.RELEASE]
> 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.3.21.RELEASE.jar:4.3.21.RELEASE]
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.35.jar:8.5.35]
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.35.jar:8.5.35]
> 	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:109) [spring-web-4.3.21.RELEASE.jar:4.3.21.RELEASE]
> 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.3.21.RELEASE.jar:4.3.21.RELEASE]
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.35.jar:8.5.35]
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.35.jar:8.5.35]
> 	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93) [spring-web-4.3.21.RELEASE.jar:4.3.21.RELEASE]
> 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.3.21.RELEASE.jar:4.3.21.RELEASE]
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.35.jar:8.5.35]
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.35.jar:8.5.35]
> 	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197) [spring-web-4.3.21.RELEASE.jar:4.3.21.RELEASE]
> 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.3.21.RELEASE.jar:4.3.21.RELEASE]
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.35.jar:8.5.35]
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.35.jar:8.5.35]
> 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198) [tomcat-embed-core-8.5.35.jar:8.5.35]
> 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [tomcat-embed-core-8.5.35.jar:8.5.35]
> 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493) [tomcat-embed-core-8.5.35.jar:8.5.35]
> 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140) [tomcat-embed-core-8.5.35.jar:8.5.35]
> 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81) [tomcat-embed-core-8.5.35.jar:8.5.35]
> 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) [tomcat-embed-core-8.5.35.jar:8.5.35]
> 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342) [tomcat-embed-core-8.5.35.jar:8.5.35]
> 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800) [tomcat-embed-core-8.5.35.jar:8.5.35]
> 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-embed-core-8.5.35.jar:8.5.35]
> 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806) [tomcat-embed-core-8.5.35.jar:8.5.35]
> 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498) [tomcat-embed-core-8.5.35.jar:8.5.35]
> 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-8.5.35.jar:8.5.35]
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_121]
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_121]
> 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-8.5.35.jar:8.5.35]
> 	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_121]
> 
> 2018-12-28 14:05:48.466  INFO 4880 --- [nio-8080-exec-1] com.alibaba.druid.pool.DruidDataSource   : {dataSource-1} inited
> 2018-12-28 14:05:48.853 ERROR 4880 --- [eate-1663236241] com.alibaba.druid.pool.DruidDataSource   : create connection error
> 
> java.lang.NoClassDefFoundError: org/elasticsearch/plugins/NetworkPlugin
> 	at java.lang.ClassLoader.defineClass1(Native Method) ~[na:1.8.0_121]
> 	at java.lang.ClassLoader.defineClass(ClassLoader.java:763) ~[na:1.8.0_121]
> 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[na:1.8.0_121]
> 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467) ~[na:1.8.0_121]
> 	at java.net.URLClassLoader.access$100(URLClassLoader.java:73) ~[na:1.8.0_121]
> 	at java.net.URLClassLoader$1.run(URLClassLoader.java:368) ~[na:1.8.0_121]
> 	at java.net.URLClassLoader$1.run(URLClassLoader.java:362) ~[na:1.8.0_121]
> 	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_121]
> 	at java.net.URLClassLoader.findClass(URLClassLoader.java:361) ~[na:1.8.0_121]
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_121]
> 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331) ~[na:1.8.0_121]
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_121]
> 	at org.elasticsearch.transport.client.PreBuiltTransportClient.<clinit>(PreBuiltTransportClient.java:86) ~[transport-5.4.1.jar:5.4.1]
> 	at com.alibaba.druid.pool.ElasticSearchConnection.<init>(ElasticSearchConnection.java:32) ~[elasticsearch-sql-5.4.1.0.jar:na]
> 	at com.alibaba.druid.pool.ElasticSearchDruidDataSource.createPhysicalConnection(ElasticSearchDruidDataSource.java:658) ~[elasticsearch-sql-5.4.1.0.jar:na]
> 	at com.alibaba.druid.pool.ElasticSearchDruidDataSource.createPhysicalConnection(ElasticSearchDruidDataSource.java:623) ~[elasticsearch-sql-5.4.1.0.jar:na]
> 	at com.alibaba.druid.pool.ElasticSearchDruidDataSource$CreateConnectionThread.run(ElasticSearchDruidDataSource.java:1802) ~[elasticsearch-sql-5.4.1.0.jar:na]
> Caused by: java.lang.ClassNotFoundException: org.elasticsearch.plugins.NetworkPlugin
> 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[na:1.8.0_121]
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_121]
> 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331) ~[na:1.8.0_121]
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_121]
> 	... 17 common frames omitted
>

**Comment by ighack** [comment]
`<dependency>
            <groupId>org.elasticsearch.client</groupId>
            <artifactId>transport</artifactId>
            <version>5.4.1</version>
        </dependency>

        <dependency>
            <groupId>org.elasticsearch</groupId>
            <artifactId>elasticsearch</artifactId>
            <version>5.4.1</version>
        </dependency>
 
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-api</artifactId>
            <version>2.6.2</version>
        </dependency>

        
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-to-slf4j</artifactId>
            <version>2.6.2</version>
        </dependency>

        
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-simple</artifactId>
            <version>1.7.21</version>
            <scope>test</scope>
        </dependency>
        
        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
            <version>27.0-jre</version>
        </dependency>`
这样添加可以运行但还是有

> c.a.d.p.v.MySqlValidConnectionChecker : Cannot resolve com.mysq.jdbc.Connection.ping method. Will use 'SELECT 1' instead.
> 
> java.lang.NullPointerException: null
> at com.alibaba.druid.pool.vendor.MySqlValidConnectionChecker.(MySqlValidConnectionChecker.java:48) ~[druid.jar:1.0.15]
> at com.alibaba.druid.pool.ElasticSearchDruidDataSource.initValidConnectionChecker(ElasticSearchDruidDataSource.java:880) [elasticsearch-sql-5.4.1.0.jar:na]

**Comment by shi-yuan** [comment]
datasource bean是如何配置的呢？又是如何使用datasource bean的，是直接用的jdbctemplate么？

**Comment by ighack** [comment]
` Properties properties = new Properties();
            properties.put(PROP_URL, "jdbc:elasticsearch://10.3.87.33:9300,10.3.87.211:9300,10.3.87.209:9300/" + "operator_stock_data");
            properties.put(PROP_CONNECTIONPROPERTIES, "client.transport.ignore_cluster_name=true");
            DruidDataSource dds = (DruidDataSource) ElasticSearchDruidDataSourceFactory.createDataSource(properties);
            Connection connection = dds.getConnection();
//            String sql1 = "select Con_Name , sum(Number_Value) from operator_stock_data where (Operation_Type='购进入库') and (KPI='件数' or KPI='条目数')";
            PreparedStatement ps = connection.prepareStatement(sql);
            ResultSet resultSet = ps.executeQuery();
            List<List<String>> result = new ArrayList<>();

            while (resultSet.next()) {
                List<String> _data = new ArrayList<>();
                for(int i=0;i<esResult.getColumnList().size();i++){
                    _data.add(String.valueOf(resultSet.getObject(esResult.getColumnList().get(i).getName())));
                }
                result.add(_data);
            }`
没有在application.properties配东西

**Comment by ighack** [comment]
driverClassName
我也不知道这个配什么东西，所以就没配任何东西

**Comment by shi-yuan** [comment]
不需要配置driverClassName，这条语句：
```sql
select Con_Name , sum(Number_Value) from operator_stock_data where (Operation_Type='购进入库') and (KPI='件数' or KPI='条目数')
```
explain后：
```json
{
  "from": 0,
  "size": 0,
  "query": {
    "bool": {
      "filter": [
        {
          "bool": {
            "must": [
              {
                "bool": {
                  "must": [
                    {
                      "match_phrase": {
                        "Operation_Type": {
                          "query": "购进入库",
                          "slop": 0,
                          "zero_terms_query": "NONE",
                          "boost": 1
                        }
                      }
                    },
                    {
                      "bool": {
                        "should": [
                          {
                            "match_phrase": {
                              "KPI": {
                                "query": "件数",
                                "slop": 0,
                                "zero_terms_query": "NONE",
                                "boost": 1
                              }
                            }
                          },
                          {
                            "match_phrase": {
                              "KPI": {
                                "query": "条目数",
                                "slop": 0,
                                "zero_terms_query": "NONE",
                                "boost": 1
                              }
                            }
                          }
                        ],
                        "adjust_pure_negative": true,
                        "boost": 1
                      }
                    }
                  ],
                  "adjust_pure_negative": true,
                  "boost": 1
                }
              }
            ],
            "adjust_pure_negative": true,
            "boost": 1
          }
        }
      ],
      "adjust_pure_negative": true,
      "boost": 1
    }
  },
  "_source": {
    "includes": [
      "Con_Name",
      "SUM"
    ],
    "excludes": []
  },
  "stored_fields": "Con_Name",
  "aggregations": {
    "SUM(Number_Value)": {
      "sum": {
        "field": "Number_Value"
      }
    }
  }
}
```

**Comment by ighack** [comment]
我想问的是
select Con_Name,Goods_Type , SUM(Number_Value + Number_Value) AS FF from operator_warehouse_data where (Operation_Type='购进入库') and (KPI='件数' or KPI='条目数') group by Con_Name,Goods_Type
FF字段总是0

这一句会报错
SUM(Number_Value) + 1 
> Error: {"error":{"root_cause":[{"type":"null_pointer_exception","reason":null}],"type":"null_pointer_exception","reason":null},"status":500}

**Comment by ighack** [comment]
> c.a.d.p.v.MySqlValidConnectionChecker : Cannot resolve com.mysq.jdbc.Connection.ping method. Will use 'SELECT 1' instead.
> java.lang.NullPointerException: null
我不想出现这个错误改怎么配啊，网上说不配spring.datasource.validationQuery就报错
spring.datasource.validationQuery=SELECT KPI FROM operator_warehouse_data limit 1
配成这样还是不行
spring.datasource.url=jdbc:elasticsearch://10.3.87.33:9300,10.3.87.211:9300,10.3.87.209:9300/operator_warehouse_data
这个能代替
properties.put(PROP_URL, "jdbc:elasticsearch://10.3.87.33:9300,10.3.87.211:9300,10.3.87.209:9300/" + "operator_stock_data");
这个吗？

**Comment by shi-yuan** [comment]
```sql
select Con_Name,Goods_Type , SUM(Number_Value + Number_Value) AS FF from operator_warehouse_data where (Operation_Type='购进入库') and (KPI='件数' or KPI='条目数') group by Con_Name,Goods_Type
```
```json
{
  "from": 0,
  "size": 0,
  "query": {
    "bool": {
      "filter": [
        {
          "bool": {
            "must": [
              {
                "bool": {
                  "must": [
                    {
                      "match_phrase": {
                        "Operation_Type": {
                          "query": "购进入库",
                          "slop": 0,
                          "zero_terms_query": "NONE",
                          "boost": 1
                        }
                      }
                    },
                    {
                      "bool": {
                        "should": [
                          {
                            "match_phrase": {
                              "KPI": {
                                "query": "件数",
                                "slop": 0,
                                "zero_terms_query": "NONE",
                                "boost": 1
                              }
                            }
                          },
                          {
                            "match_phrase": {
                              "KPI": {
                                "query": "条目数",
                                "slop": 0,
                                "zero_terms_query": "NONE",
                                "boost": 1
                              }
                            }
                          }
                        ],
                        "adjust_pure_negative": true,
                        "boost": 1
                      }
                    }
                  ],
                  "adjust_pure_negative": true,
                  "boost": 1
                }
              }
            ],
            "adjust_pure_negative": true,
            "boost": 1
          }
        }
      ],
      "adjust_pure_negative": true,
      "boost": 1
    }
  },
  "_source": {
    "includes": [
      "Con_Name",
      "Goods_Type",
      "SUM"
    ],
    "excludes": []
  },
  "stored_fields": [
    "Con_Name",
    "Goods_Type"
  ],
  "aggregations": {
    "Con_Name": {
      "terms": {
        "field": "Con_Name",
        "size": 200,
        "min_doc_count": 1,
        "shard_min_doc_count": 0,
        "show_term_doc_count_error": false,
        "order": [
          {
            "_count": "desc"
          },
          {
            "_key": "asc"
          }
        ]
      },
      "aggregations": {
        "Goods_Type": {
          "terms": {
            "field": "Goods_Type",
            "size": 10,
            "min_doc_count": 1,
            "shard_min_doc_count": 0,
            "show_term_doc_count_error": false,
            "order": [
              {
                "_count": "desc"
              },
              {
                "_key": "asc"
              }
            ]
          },
          "aggregations": {
            "FF": {
              "sum": {
                "script": {
                  "source": " def add_754649670 = doc['Number_Value'].value + doc['Number_Value'].value;return add_754649670;",
                  "lang": "painless"
                }
              }
            }
          }
        }
      }
    }
  }
}
```

**Comment by shi-yuan** [comment]
SUM(Number_Value) + 1，这个是不支持的哦
