### ISSUE TITLE
date_histogram空桶执行出错

### ISSUE THREAD

**Issue by vichWei** [NLPchina/elasticsearch-sql#855]
sql用法：date_histogram(field='aiops_timestamp','interval'='1d','alias'='aiops_timestamp','min_doc_count'='0','extended_bounds'='1547083500000:1547343000000')
--------------------
执行报错如下：
------------
log4j:WARN No appenders could be found for logger (com.alibaba.druid.pool.vendor.MySqlValidConnectionChecker).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console.
java.sql.SQLException: Error
	at com.alibaba.druid.pool.ElasticSearchDruidDataSource.handleConnectionException(ElasticSearchDruidDataSource.java:1109)
	at com.alibaba.druid.pool.DruidPooledConnection.handleException(DruidPooledConnection.java:127)
	at com.alibaba.druid.pool.DruidPooledStatement.checkException(DruidPooledStatement.java:68)
	at com.alibaba.druid.pool.ElasticSearchDruidPooledPreparedStatement.executeQuery(ElasticSearchDruidPooledPreparedStatement.java:61)
	at org.nlpcn.es4sql.Main2.main(Main2.java:90)
Caused by: Failed to execute phase [query], all shards failed; shardFailures {[d0r7oc3TS6eR-sR9A_1_gA][aiops_log][0]: RemoteTransportException[[10.10.100.237][10.10.100.237:9300][indices:data/read/search[phase/query]]]; nested: ElasticsearchParseException[failed to parse date field [1547083500000] with format [yyyy-MM-dd HH:mm:ss]]; nested: IllegalArgumentException[Parse failure at index [9] of [1547083500000]]; }{[d0r7oc3TS6eR-sR9A_1_gA][aiops_log][1]: RemoteTransportException[[10.10.100.237][10.10.100.237:9300][indices:data/read/search[phase/query]]]; nested: ElasticsearchParseException[failed to parse date field [1547083500000] with format [yyyy-MM-dd HH:mm:ss]]; nested: IllegalArgumentException[Parse failure at index [9] of [1547083500000]]; }{[d0r7oc3TS6eR-sR9A_1_gA][aiops_log][2]: RemoteTransportException[[10.10.100.237][10.10.100.237:9300][indices:data/read/search[phase/query]]]; nested: ElasticsearchParseException[failed to parse date field [1547083500000] with format [yyyy-MM-dd HH:mm:ss]]; nested: IllegalArgumentException[Parse failure at index [9] of [1547083500000]]; }{[EGg0HOPrTByzU9egjW_fnw][aiops_log][3]: RemoteTransportException[[10.10.100.236][10.10.100.236:9300][indices:data/read/search[phase/query]]]; nested: ElasticsearchParseException[failed to parse date field [1547083500000] with format [yyyy-MM-dd HH:mm:ss]]; nested: IllegalArgumentException[Parse failure at index [9] of [1547083500000]]; }{[d0r7oc3TS6eR-sR9A_1_gA][aiops_log][4]: RemoteTransportException[[10.10.100.237][10.10.100.237:9300][indices:data/read/search[phase/query]]]; nested: ElasticsearchParseException[failed to parse date field [1547083500000] with format [yyyy-MM-dd HH:mm:ss]]; nested: IllegalArgumentException[Parse failure at index [9] of [1547083500000]]; }
	at org.elasticsearch.action.search.AbstractSearchAsyncAction.onInitialPhaseResult(AbstractSearchAsyncAction.java:223)
	at org.elasticsearch.action.search.AbstractSearchAsyncAction.access$100(AbstractSearchAsyncAction.java:58)
	at org.elasticsearch.action.search.AbstractSearchAsyncAction$1.onFailure(AbstractSearchAsyncAction.java:148)
	at org.elasticsearch.action.ActionListenerResponseHandler.handleException(ActionListenerResponseHandler.java:51)
	at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:1032)
	at org.elasticsearch.transport.TcpTransport.lambda$handleException$17(TcpTransport.java:1411)
	at org.elasticsearch.common.util.concurrent.EsExecutors$1.execute(EsExecutors.java:109)
	at org.elasticsearch.transport.TcpTransport.handleException(TcpTransport.java:1409)
	at org.elasticsearch.transport.TcpTransport.handlerResponseError(TcpTransport.java:1401)
	at org.elasticsearch.transport.TcpTransport.messageReceived(TcpTransport.java:1345)
	at org.elasticsearch.transport.netty4.Netty4MessageChannelHandler.channelRead(Netty4MessageChannelHandler.java:74)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:280)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:396)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:129)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:642)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:527)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:481)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:441)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Thread.java:745)
Caused by: RemoteTransportException[[10.10.100.237][10.10.100.237:9300][indices:data/read/search[phase/query]]]; nested: ElasticsearchParseException[failed to parse date field [1547083500000] with format [yyyy-MM-dd HH:mm:ss]]; nested: IllegalArgumentException[Parse failure at index [9] of [1547083500000]];
Caused by: ElasticsearchParseException[failed to parse date field [1547083500000] with format [yyyy-MM-dd HH:mm:ss]]; nested: IllegalArgumentException[Parse failure at index [9] of [1547083500000]];
	at org.elasticsearch.common.joda.DateMathParser.parseDateTime(DateMathParser.java:213)
	at org.elasticsearch.common.joda.DateMathParser.parse(DateMathParser.java:66)
	at org.elasticsearch.search.DocValueFormat$DateTime.parseLong(DocValueFormat.java:170)
	at org.elasticsearch.search.aggregations.bucket.histogram.ExtendedBounds.parseAndValidate(ExtendedBounds.java:156)
	at org.elasticsearch.search.aggregations.bucket.histogram.DateHistogramAggregationBuilder.innerBuild(DateHistogramAggregationBuilder.java:329)
	at org.elasticsearch.search.aggregations.support.ValuesSourceAggregationBuilder.doBuild(ValuesSourceAggregationBuilder.java:291)
	at org.elasticsearch.search.aggregations.support.ValuesSourceAggregationBuilder.doBuild(ValuesSourceAggregationBuilder.java:39)
	at org.elasticsearch.search.aggregations.AbstractAggregationBuilder.build(AbstractAggregationBuilder.java:126)
	at org.elasticsearch.search.aggregations.AggregatorFactories$Builder.build(AggregatorFactories.java:333)
	at org.elasticsearch.search.SearchService.parseSource(SearchService.java:637)
	at org.elasticsearch.search.SearchService.createContext(SearchService.java:468)
	at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:444)
	at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:252)
	at org.elasticsearch.action.search.SearchTransportService$6.messageReceived(SearchTransportService.java:331)
	at org.elasticsearch.action.search.SearchTransportService$6.messageReceived(SearchTransportService.java:328)
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:69)
	at org.elasticsearch.transport.TcpTransport$RequestHandler.doRun(TcpTransport.java:1488)
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:638)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: Parse failure at index [9] of [1547083500000]
	at org.elasticsearch.common.joda.DateMathParser.parseDateTime(DateMathParser.java:207)
	... 21 more
{"msg":"FAILURE","code":-1,"dataList":[]}

**Comment by shi-yuan** [comment]
格式不匹配，默认是yyyy-MM-dd HH:mm:ss，加个format吧，改成：
````
date_histogram(field='aiops_timestamp','interval'='1d','alias'='aiops_timestamp','min_doc_count'='0','extended_bounds'='1547083500000:1547343000000',format='epoch_millis')
````

**Comment by vichWei** [comment]
@shi-yuan 谢谢回复，测试了，加上format不会报错，但是没有返回空桶
如sql语句，我查询的范围是2019-01-10 00:00:00--2019-01-14 00:00:00，extended_bounds的时间戳范围也是这个范围
sql如下----：
select aiops_endpoint.keyword as aiops_endpoint,count(*) as count from aiops_log* where aiops_timestamp >= '2019-01-10T00:00:00.000Z' and aiops_timestamp < '2019-01-14T00:00:00.000Z' group by date_histogram(field='aiops_timestamp','interval'='1d','alias'='aiops_timestamp',**'min_doc_count'='0','extended_bounds'='1547049600000:1547395200000',format='epoch_millis'**),aiops_endpoint
没有返回01-12日的空桶数据，结果如下-----:
{"msg":"SUCCESS","code":0,"dataList":[{"aiops_timestamp":"1547078400000","aiops_endpoint":"10.10.100.235:8000","count":2058},{"aiops_timestamp":"1547164800000","aiops_endpoint":"10.10.100.235:8000","count":9507},{"aiops_timestamp":"1547337600000","aiops_endpoint":"10.10.100.235:8000","count":2458}]}
这三条数据依次为（没有从00点开始聚类）：
2019-01-10 08:00:00
2019-01-11 08:00:00
2019-01-13 08:00:00

我的理想结果是这样，不希望查询出来的数据，再转一次时间，并且按天是从00点开始，
但extended_bounds的参数只接受long型
执行：
select aiops_endpoint.keyword as aiops_endpoint,count(*) as count from aiops_log* where aiops_timestamp >= '2019-01-10T00:00:00.000Z' and aiops_timestamp < '2019-01-14T00:00:00.000Z' group by date_histogram(field='aiops_timestamp','interval'='1d','alias'='aiops_timestamp'),aiops_endpoint
返回：
{"msg":"SUCCESS","code":0,"dataList":[
{"aiops_timestamp":"2019-01-10 00:00:00","aiops_endpoint":"10.10.100.235:8000","count":13167},{"aiops_timestamp":"2019-01-11 00:00:00","aiops_endpoint":"10.10.100.235:8000","count":9507},{"aiops_timestamp":"2019-01-13 00:00:00","aiops_endpoint":"10.10.100.235:8000","count":2984}]}

**我用的es sql版本为5.6.9**

**Comment by vichWei** [comment]
@shi-yuan 请看代码：）
public static void main(String[] args){
		Properties properties = new Properties();
		String url = "jdbc:elasticsearch://10.10.100.235:9300"; 
		properties.put("url", url);
		String sql = "select aiops_endpoint.keyword as aiops_endpoint,count(*) as count from aiops_log* where aiops_timestamp >= '2019-01-10T00:00:00.000Z' and aiops_timestamp < '2019-01-14T00:00:00.000Z' group by date_histogram(field='aiops_timestamp','interval'='1d','alias'='aiops_timestamp','min_doc_count'='0','extended_bounds'='1547049600000:1547395200000',format='epoch_millis'),aiops_endpoint";
		List<LinkedHashMap<String, Object>> dataList = new ArrayList<LinkedHashMap<String, Object>>();
		JSONObject json = new JSONObject();
     	String msg = "SUCCESS";
     	int code = 0;
     	try( DruidDataSource dds = (DruidDataSource) ElasticSearchDruidDataSourceFactory.createDataSource(properties);
             Connection connection = dds.getConnection();
             PreparedStatement ps = connection.prepareStatement(sql);) {
	         ResultSet resultSet = ps.executeQuery();
	         ResultSetMetaData md = resultSet.getMetaData();
	         int columnCount = md.getColumnCount();
	         List<String> list = new ArrayList<String>();
	         for (int i = 1; i <= columnCount; i++) {
	         	list.add(md.getColumnName(i));
	         }
	         if(list != null && list.size() > 0) {
	         	while (resultSet.next()) {
	         		LinkedHashMap<String, Object> rowData = new LinkedHashMap<String, Object>();
	         		Boolean flag = true;
	                 for (int i = 0; i < list.size(); i++) {
	                 	String column = list.get(i);
	                 	try{
	                 		rowData.put(column, resultSet.getObject(column));
	                 	} catch (Exception e) {
	                 		System.out.println("resultSet获取数据失败，继续获取...");
	                 		flag = false;
	                 		break;
	                 	}
	                 }
	                 if(flag) {
	                 	dataList.add(rowData);
	                 }
	                 
	             }
	         }
		} catch (Exception e) {
			msg = "FAILURE";
			code = -1;
			e.printStackTrace();
		}
	 	 json.put("msg", msg);
	     json.put("code", code);
	     json.put("dataList", dataList);
	     System.out.println(json.toJSONString());
	}

**Comment by shi-yuan** [comment]
如果不设置'min_doc_count'='0','extended_bounds'='1547049600000:1547395200000',format='epoch_millis'，加上时区，'time_zone'='+08:00'，否则返回的是UTC时间
