### ISSUE TITLE
ERROR com.alibaba.druid.pool.DruidDataSource - create connection error

### ISSUE THREAD

**Issue by HernanMora** [NLPchina/elasticsearch-sql#875]
Trying to execute the following code on Elasticsearch 6.5.4

```
        try {
            String url = "jdbc:elasticsearch://localhost:9200/my_index";
            Properties properties = new Properties();
            properties.put(PROP_URL, url);
            properties.put(PROP_CONNECTIONPROPERTIES, "cluster.name=elasticsearch");
            DruidDataSource dds = (DruidDataSource) ElasticSearchDruidDataSourceFactory.createDataSource(properties);
            Connection connection = dds.getConnection();
            PreparedStatement ps = connection.prepareStatement("SELECT * FROM my_index LIMIT 1");
            ResultSet resultSet = ps.executeQuery();
            List<String> result = new ArrayList<String>();
            while (resultSet.next()) {
                result.add(resultSet.getString("message"));
            }
            ps.close();
            connection.close();
            dds.close();
        } catch (Exception e) {
            System.out.println(e.getMessage());
            e.printStackTrace();
        }
```
I get the following error

`ERROR com.alibaba.druid.pool.DruidDataSource - create connection error
java.lang.InstantiationError: org.elasticsearch.common.transport.TransportAddress
	at com.alibaba.druid.pool.ElasticSearchDruidDataSource.createPhysicalConnection(ElasticSearchDruidDataSource.java:680)
	at com.alibaba.druid.pool.ElasticSearchDruidDataSource.createPhysicalConnection(ElasticSearchDruidDataSource.java:632)
	at com.alibaba.druid.pool.ElasticSearchDruidDataSource$CreateConnectionThread.run(ElasticSearchDruidDataSource.java:1841)`

Project dependencies:
    compile files('libs/elasticsearch-sql-6.5.4.7.jar')
    compile files('libs/druid.jar')
    compile files('libs/guava.jar')
    compile files('libs/parent-join-client-6.5.4.jar')
    compile files('libs/reindex-client-6.5.4.jar')
    compile("org.elasticsearch.client:transport:6.5.4")

**Comment by shi-yuan** [comment]
add dependency:
```xml
<repositories>
	<repository>
		<id>elasticsearch-releases</id>
		<url>https://artifacts.elastic.co/maven</url>
		<releases>
			<enabled>true</enabled>
		</releases>
		<snapshots>
			<enabled>false</enabled>
		</snapshots>
	</repository>
</repositories>

<dependencies>
	...
	<dependency>
		<groupId>org.elasticsearch</groupId>
		<artifactId>elasticsearch</artifactId>
		<version>6.5.4</version>
	</dependency>

	<dependency>
		<groupId>org.elasticsearch.client</groupId>
		<artifactId>x-pack-transport</artifactId>
		<version>6.5.4</version>
	</dependency>
	...
</dependencies>
```
