### ISSUE TITLE
index名称不支持横线

### ISSUE THREAD

**Issue by Birdflying1005** [NLPchina/elasticsearch-sql#955]
如果index名称中有横线，会报druid parser错误。

```
com.alibaba.druid.sql.parser.ParserException: ERROR. token : ANALYZE, pos : 38
	at com.alibaba.druid.sql.parser.SQLExprParser.primary(SQLExprParser.java:555)
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlExprParser.primary(MySqlExprParser.java:166)
	at com.alibaba.druid.sql.parser.SQLExprParser.bitXor(SQLExprParser.java:147)
	at com.alibaba.druid.sql.parser.SQLExprParser.multiplicative(SQLExprParser.java:163)
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlExprParser.additiveRest(MySqlExprParser.java:610)
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlExprParser.additiveRest(MySqlExprParser.java:613)
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlExprParser.additiveRest(MySqlExprParser.java:613)
	at com.alibaba.druid.sql.parser.SQLExprParser.exprRest(SQLExprParser.java:133)
```

**Comment by shi-yuan** [comment]
试试：
```sql
SELECT * FROM ['888afc4c-1b45-4e2b-bac7-e51635bd5f70-888afc4c-1b45-4e2b-bac7-e51635bd5f70-abc'] WHERE ['last name']='bar'
```

**Comment by YouXiang-Wang** [comment]
Work as design
