### ISSUE TITLE
es 6.6.0集群异常

### ISSUE THREAD

**Issue by OneJane** [NLPchina/elasticsearch-sql#961]
## 源代码
```
public class Test {
 
	public static void main(String[] args) throws Exception {
		Properties properties = new Properties();
		properties.put("url", "jdbc:elasticsearch://192.168.2.7:1801,192.168.2.5:1801/"+"t_word_freq");
		DruidDataSource dds = (DruidDataSource) ElasticSearchDruidDataSourceFactory.createDataSource(properties);
		dds.setInitialSize(1);
		Connection connection = dds.getConnection();
		String sql2 = "select * FROM t_word_freq limit 10";
		PreparedStatement ps = connection.prepareStatement(sql2);
		ResultSet resultSet = ps.executeQuery();
		while (resultSet.next()) {
		    //sql对应输出
		    System.out.println(resultSet.getString("info.url") );
 
		}
		ps.close();
		connection.close();
		dds.close();
	}
}
```
## 报错
```
Exception in thread "main" java.lang.NoSuchFieldError: createErrorCount
	at com.alibaba.druid.pool.ElasticSearchDruidDataSource.createPhysicalConnection(ElasticSearchDruidDataSource.java:655)
	at com.alibaba.druid.pool.ElasticSearchDruidDataSource.init(ElasticSearchDruidDataSource.java:579)
	at com.alibaba.druid.pool.ElasticSearchDruidDataSource.getConnection(ElasticSearchDruidDataSource.java:930)
	at com.alibaba.druid.pool.ElasticSearchDruidDataSource.getConnection(ElasticSearchDruidDataSource.java:926)
	at com.ht.micro.record.service.dubbo.provider.controller.Test.main(Test.java:19)
```

**Comment by OneJane** [comment]
@shi-yuan 请问一下 是哪里配置错误了吗，我这里端口9300->1801,9200->1800

**Comment by OneJane** [comment]
我加入依赖后
```
<dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>druid</artifactId>
            <version>1.0.15</version>
        </dependency>
        <dependency>
            <groupId>org.elasticsearch</groupId>
            <artifactId>elasticsearch</artifactId>
            <version>6.6.0</version>
        </dependency>
        <dependency>
            <groupId>org.elasticsearch.client</groupId>
            <artifactId>transport</artifactId>
            <version>6.6.0</version>
            <exclusions>
                <exclusion>
                    <groupId>org.elasticsearch.plugin</groupId>
                    <artifactId>transport-netty4-client</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.elasticsearch.plugin</groupId>
            <artifactId>transport-netty4-client</artifactId>
            <version>6.6.0</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
        </dependency>
        <dependency>
            <groupId>com.github.jsqlparser</groupId>
            <artifactId>jsqlparser</artifactId>
            <version>1.3</version>
        </dependency>
```
报新的错误如下
```
Exception in thread "main" java.lang.NoClassDefFoundError: org/elasticsearch/xpack/client/PreBuiltXPackTransportClient
	at com.alibaba.druid.pool.ElasticSearchDruidDataSource.createPhysicalConnection(ElasticSearchDruidDataSource.java:686)
	at com.alibaba.druid.pool.ElasticSearchDruidDataSource.createPhysicalConnection(ElasticSearchDruidDataSource.java:632)
	at com.alibaba.druid.pool.ElasticSearchDruidDataSource.init(ElasticSearchDruidDataSource.java:579)
	at com.alibaba.druid.pool.ElasticSearchDruidDataSource.getConnection(ElasticSearchDruidDataSource.java:930)
	at com.alibaba.druid.pool.ElasticSearchDruidDataSource.getConnection(ElasticSearchDruidDataSource.java:926)
	at com.ht.micro.record.service.dubbo.provider.controller.Test.main(Test.java:20)
Caused by: java.lang.ClassNotFoundException: org.elasticsearch.xpack.client.PreBuiltXPackTransportClient
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 6 more
```

**Comment by OneJane** [comment]
![image](https://user-images.githubusercontent.com/15198872/63421128-a3fe2580-c43a-11e9-9845-c23f5f116f48.png)
报错在这一行

**Comment by shi-yuan** [comment]
client包换下：
```xml
<repositories>
	<repository>
		<id>elasticsearch-releases</id>
		<url>https://artifacts.elastic.co/maven</url>
		<releases>
			<enabled>true</enabled>
		</releases>
		<snapshots>
			<enabled>false</enabled>
		</snapshots>
	</repository>
</repositories>

<dependencies>
    ...
    <dependency>
        <groupId>org.elasticsearch.client</groupId>
        <artifactId>x-pack-transport</artifactId>
        <version>${elasticsearch.version}</version>
        <scope>provided</scope>
    </dependency>
    ...
</dependencies>
```

**Comment by OneJane** [comment]
> client包换下：
> 
> ```
> <repositories>
> 	<repository>
> 		<id>elasticsearch-releases</id>
> 		<url>https://artifacts.elastic.co/maven</url>
> 		<releases>
> 			<enabled>true</enabled>
> 		</releases>
> 		<snapshots>
> 			<enabled>false</enabled>
> 		</snapshots>
> 	</repository>
> </repositories>
> 
> <dependencies>
>     ...
>     <dependency>
>         <groupId>org.elasticsearch.client</groupId>
>         <artifactId>x-pack-transport</artifactId>
>         <version>${elasticsearch.version}</version>
>         <scope>provided</scope>
>     </dependency>
>     ...
> </dependencies>
> ```

嗯 尝试了，
- 目前问题druid使用1.0.15会项目启动报NoClassDefFoundError: com/alibaba/druid/filter/logging/Log4j2Filter，单独test可以跑
- druid使用1.1.16报错java.lang.NoSuchFieldError: createErrorCount，java.lang.NoSuchFieldError: createErrorCount没有这个方法
