### ISSUE TITLE
求救大佬，快救命，今天弄了一天了:elasticsearch-sql-7.4.1 安装后重启elasticsearch出现的问题非常怪异

### ISSUE THREAD

**Issue by benj201008** [NLPchina/elasticsearch-sql#994]
problem:
org.elasticsearch.bootstrap.StartupException: java.lang.IllegalArgumentException: Cannot replace existing handler for [/_sql] for method: POST

deploy steps：
1、安装:elasticsearch-sql-7.4.1
      /opt/elasticsearch 三个节点启动正常没问题
2、/opt/elasticsearch/bin/elasticsearch-plugin install https://github.com/NLPchina/elasticsearch-sql/releases/download/7.4.1.0/elasticsearch-sql-7.4.1.0.zip
     在三个节点下同时下载成功，或者尝试只在一个节点上下载成功
    future versions of Elasticsearch will require Java 11; your Java version from 
   [/usr/java/jdk1.8.0_231/jre] does not meet this requirement
    -> Downloading https://github.com/NLPchina/elasticsearch- 
   sql/releases/download/7.4.1.0/elasticsearch-sql-7.4.1.0.zip
   [=================================================] 100%   
   -> Installed sql
   出现结果:
          /opt/elasticsearch/plugins/sql
                -rw-r--r-- 1 esuser root 2769940 10月 28 13:24 druid-1.1.16.jar
               -rw-r--r-- 1 esuser root  340976 10月 28 13:24 elasticsearch-sql-7.4.1.0.jar
               -rw-r--r-- 1 esuser root 2172168 10月 28 13:24 guava-15.0.jar
               -rw-r--r-- 1 esuser root  114808 10月 28 13:24 reindex-client-7.4.1.jar
              -rw-r--r-- 1 esuser root     352 10月 28 13:24 plugin-descriptor.properties
              -rw-r--r-- 1 esuser root   81993 10月 28 13:24 parent-join-client-7.4.1.jar
3、ps -ef |grep elastic  存在，删除进程
      kill elastic进程
      ps  -ef|grep elastic 不存在，成功了
4、重启elasticsearch,启动不成功
    using discovery type [zen] and seed hosts providers [settings]
[2019-10-28T13:34:38,100][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [node-1] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: java.lang.IllegalArgumentException: Cannot replace existing handler for [/_sql] for method: POST
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:163) ~[elasticsearch-7.4.1.jar:7.4.1]
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:150) ~[elasticsearch-7.4.1.jar:7.4.1]
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) ~[elasticsearch-7.4.1.jar:7.4.1]
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:125) ~[elasticsearch-cli-7.4.1.jar:7.4.1]
        at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-cli-7.4.1.jar:7.4.1]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:115) ~[elasticsearch-7.4.1.jar:7.4.1]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92) ~[elasticsearch-7.4.1.jar:7.4.1]
Caused by: java.lang.IllegalArgumentException: Cannot replace existing handler for [/_sql] for method: POST
        at org.elasticsearch.rest.MethodHandlers.addMethods(MethodHandlers.java:52) ~[elasticsearch-7.4.1.jar:7.4.1]
        at org.elasticsearch.rest.RestController.lambda$registerHandler$1(RestController.java:156) ~[elasticsearch-7.4.1.jar:7.4.1]
        at org.elasticsearch.common.path.PathTrie$TrieNode.insertOrUpdate(PathTrie.java:167) ~[elasticsearch-7.4.1.jar:7.4.1]
        at org.elasticsearch.common.path.PathTrie$TrieNode.access$400(PathTrie.java:76) ~[elasticsearch-7.4.1.jar:7.4.1]
        at org.elasticsearch.common.path.PathTrie.insertOrUpdate(PathTrie.java:316) ~[elasticsearch-7.4.1.jar:7.4.1]
        at org.elasticsearch.rest.RestController.registerHandler(RestController.java:155) ~[elasticsearch-7.4.1.jar:7.4.1]
        at org.elasticsearch.plugin.nlpcn.RestSqlAction.<init>(RestSqlAction.java:35) ~[?:?]
        at org.elasticsearch.plugin.nlpcn.SqlPlug.getRestHandlers(SqlPlug.java:35) ~[?:?]
        at org.elasticsearch.action.ActionModule.initRestHandlers(ActionModule.java:692) ~[elasticsearch-7.4.1.jar:7.4.1]
        at org.elasticsearch.node.Node.<init>(Node.java:609) ~[elasticsearch-7.4.1.jar:7.4.1]
        at org.elasticsearch.node.Node.<init>(Node.java:255) ~[elasticsearch-7.4.1.jar:7.4.1]
        at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:221) ~[elasticsearch-7.4.1.jar:7.4.1]
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:221) ~[elasticsearch-7.4.1.jar:7.4.1]
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:349) ~[elasticsearch-7.4.1.jar:7.4.1]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159) ~[elasticsearch-7.4.1.jar:7.4.1]

**Comment by benj201008** [comment]
不知道什么原因，居然这次用新版本栽了。
vi elasticsearch.yml
http.cors.enabled: true
http.cors.allow-origin: "*"
action.destructive_requires_name: true
action.auto_create_index: .security,.monitoring*,.watches,.triggered_watches,.watcher-history*
xpack.security.enabled: false
xpack.monitoring.enabled: true
xpack.graph.enabled: false
xpack.watcher.enabled: false
xpack.ml.enabled: false
添加了这些参数，其他参数，如果需要我再贴出来，期望能看到大佬们的回音。我的微信可加:396230655

**Comment by benj201008** [comment]
我所有的环境在 centos 7.4 x64进行

**Comment by benj201008** [comment]
从https://github.com/NLPchina/elasticsearch-sql/issues/989受到启发
elasticsearch-sql与它的本机x-pack-sql模块有你没我

vi /opt/elasticsearch/config/elasticsearch.yml 修改
xpack.sql.enabled: false
重启ES
ps -ef |grep elastic 存在，删除进程
kill elastic进程
ps -ef|grep elastic 不存在
/opt/elasticsearch/bin/elasticsearch -d

**Comment by benj201008** [comment]
vi /opt/elasticsearch/config/elasticsearch.yml 修改
xpack.sql.enabled: false
重启ES

**Comment by shi-yuan** [comment]
目前插件的path和官方的sql插件path冲突了。。。
